Repository nvaccess/nvda, pull requests merged in 2018-03, with the labels that each got.

#8051 Fix problems with ALVA protocol converter and time synchronisation
  source/braille.py
  source/brailleDisplayDrivers/alva.py
Labels: Braille

#7997 Better handle dead caret / selection text ranges in Microsoft Edge
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/UIA/edge.py
  source/UIABrowseMode.py
Labels: incubating

#7992 Expose available UIA patterns in developer info
  source/NVDAObjects/UIA/__init__.py
Labels: incubating, quick fix

#7989 No longer announce final character of Windows 10 security PIN
  source/NVDAObjects/__init__.py
  source/api.py
Labels: incubating

#7988 Stop labels for checkboxes / radioButtons from being reported twice when tabbing / quicknavving in browse Mode, for Chrome / Firefox.
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
Labels: incubating

#7872 Report row and column span for table cells in speech and braille
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/__init__.py
  source/braille.py
  source/compoundDocuments.py
  source/speech.py
Labels: incubating

#7901 Handle aria-current=false as False instead of True
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/UIA/edge.py
  source/NVDAObjects/__init__.py
  source/virtualBuffers/MSHTML.py
  source/virtualBuffers/gecko_ia2.py
Labels: Browse mode, incubating

#7930 Change status column of addons to enabled or disabled
  source/gui/addonGui.py
  user_docs/en/userGuide.t2t
Labels: incubating

#7946 Allow table navigation commands in Google Docs
  source/NVDAObjects/IAccessible/ia2Web.py
Labels: incubating

#7980 Allow setting good UIA windows in core or per appModule
  source/_UIAHandler.py
  source/appModuleHandler.py
Labels: incubating

#7977 Support tables in Kindle for PC
  source/NVDAObjects/IAccessible/__init__.py
  source/appModules/kindle.py
  source/virtualBuffers/gecko_ia2.py
Labels: incubating

#8031 Support the BrailleNote Touch and Brailliant BI 14 via the BrailliantB brailledisplayDriver
  source/brailleDisplayDrivers/brailliantB.py
  source/hwIo.py
  source/hwPortUtils.py
  user_docs/en/userGuide.t2t
Labels: Braille, incubating

#8046 Ensure NVDA can switch from browseMode to focus mode in Microsoft word when using UIA and braille.
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/UIA/wordDocument.py
  source/UIABrowseMode.py
  source/review.py
Labels: Braille, incubating

#6778 Map PUA bullets to Unicode in Word
  source/NVDAObjects/window/winword.py
  source/locale/en/symbols.dic
Labels: incubating, quick fix

#7189 Add "report formatting for text under braille cell" command
  source/braille.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/eurobraille.py
  source/brailleDisplayDrivers/papenmeier.py
  source/brailleDisplayDrivers/papenmeier_serial.py
  source/globalCommands.py
  source/ui.py
  user_docs/en/userGuide.t2t
Labels: incubating

#6355 Introduse the ability to postpone a downloaded update #4263
  source/config/__init__.py
  source/config/configSpec.py
  source/core.py
  source/gui/__init__.py
  source/gui/settingsDialogs.py
  source/updateCheck.py
  user_docs/en/userGuide.t2t
Labels: incubating
