Repository nvaccess/nvda, pull requests merged in 2018-04, with the labels that each got.

#8159 Build the NVDA Controller client zip archive for release builds
  appveyor.yml
Labels: quick fix

#7843 Braille input: emulate keys outside text content and support combining input with modifiers
  source/braille.py
  source/brailleDisplayDrivers/eurobraille.py
  source/brailleInput.py
  source/globalCommands.py
  source/keyboardHandler.py
  user_docs/en/userGuide.t2t
Labels: Braille, Browse mode, incubating

#8141 log.debugWarning should not raise UnicodeDecodeError when WindowsError occurs
  source/synthDrivers/oneCore.py
  source/winConsoleHandler.py
Labels: incubating

#8138 Explorer: do not announce 'unknown' when opening quick link menu and selecting items from it (Windows+X)
  source/appModules/explorer.py
Labels: incubating

#8100 Fix model specific gestures for Hims displays
  source/braille.py
  source/brailleDisplayDrivers/hims.py
  tests/unit/test_braille.py
Labels: incubating

#8075 Provide a tool to re-register particular COM interfaces that may become unregistered or broken by uninstallers, breaking platform accessibility
  source/COMRegistrationFixes/__init__.py
  source/COMRegistrationFixes/oleaccProxy.reg
  source/gui/__init__.py
  source/installer.py
  source/nvda_slave.pyw
  source/setup.py
Labels: incubating

#8147 Add a appModule for taskMan, to fix some bugs in windows ten.
  source/appModules/taskmgr.py
Labels: incubating

#7949 Improve working with message lists and calendars in Outlook
  source/appModules/outlook.py
  source/globalCommands.py
  source/winKernel.py
Labels: Microsoft Office support, incubating, quick fix

#7302 Change multiple settings dialogs into one category based dialog
  source/api.py
  source/appModules/nvda.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/__init__.py
  source/gui/guiHelper.py
  source/gui/settingsDialogs.py
  source/synthDriverHandler.py
  source/windowUtils.py
  user_docs/en/userGuide.t2t
Labels: NVDA GUI, incubating

#5937 Enhanced readability of script_moveMouseToNavigatorObject
  source/globalCommands.py
Labels: incubating

#8176 Use OneCore speech on windows 10 by default rather than eSpeak
  source/synthDriverHandler.py
Labels: incubating

#8174 Allow SAPI5 voices to be instantly interupted / paused by making use of the underlying ISPAudio interface.
  source/synthDrivers/sapi5.py
Labels: incubating
