Repository nvaccess/nvda, pull requests merged in 2018-07, with the labels that each got.

#8446 {liblouis3.6.0 brailletables}
  source/brailleTables.py
  user_docs/en/changes.t2t
Labels: incubating

#7741 Add automatic background braille display detection
  source/appModuleHandler.py
  source/bdDetect.py
  source/braille.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/baum.py
  source/brailleDisplayDrivers/brailleNote.py
  source/brailleDisplayDrivers/brailliantB.py
  source/brailleDisplayDrivers/eurobraille.py
  source/brailleDisplayDrivers/handyTech.py
  source/brailleDisplayDrivers/hims.py
  source/brailleDisplayDrivers/superBrl.py
  source/config/configSpec.py
  source/core.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/hwIo.py
  source/hwPortUtils.py
  source/winKernel.py
  source/winUser.py
  tests/unit/__init__.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: Braille, incubating

#8449 Support aria-roledescription in Edge.
  source/NVDAObjects/UIA/edge.py
  source/braille.py
  source/browseMode.py
  user_docs/en/changes.t2t
Labels: incubating

#8374 Microsoft Store edition: detect if this is just a package or not (check error 15700)
  source/nvda.pyw
Labels: incubating

#8230 Several fixes to the ALVA driver
  source/braille.py
  source/brailleDisplayDrivers/alva.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: incubating

#8401 Improve reporting keyboard layout changes
  nvdaHelper/remote/tsf.cpp
  source/NVDAHelper.py
  user_docs/en/changes.t2t
Labels: incubating

#8397 Fix getting offsets from points in edit controls when offset numbers exceed 16 bits
  source/NVDAObjects/window/edit.py
  user_docs/en/changes.t2t
Labels: incubating

#7378 Composable Shell touch keyboard: support emoji panel and other features in Windows 10 Fall Creators Update and later. re #7273
  source/appModules/windowsinternal_composableshell_experiences_textinput_inputapp.py
  user_docs/en/changes.t2t
Labels: incubating

#7537 Provide a locationHelper module for code related to locations, rectangles and points
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/IAccessible/sysListView32.py
  source/NVDAObjects/JAB/__init__.py
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/window/__init__.py
  source/appModules/powerpnt.py
  source/displayModel.py
  source/locationHelper.py
  source/textInfos/__init__.py
  source/winUser.py
  tests/unit/test_locationHelper.py
Labels: incubating

#8578 Fix mistake in freedomScientific keymap assignment
  source/brailleDisplayDrivers/freedomScientific.py
Labels: Braille, quick fix
