Repository nvaccess/nvda, pull requests merged in 2018-05, with the labels that each got.

#8234 Properly show both the alt and windows key toggle gestures in the input gestures dialog
  source/globalCommands.py
Labels: quick fix

#5751 Filter LTR and RTL marks from list view items
  source/NVDAObjects/IAccessible/sysListView32.py
  source/appModules/explorer.py
Labels: incubating, quick fix

#8186 Update the examples used in GUI helper.
  source/gui/guiHelper.py
Labels: incubating

#6488 Add an input gesture to temporarily disable all configuration profiles
  source/globalCommands.py
  user_docs/en/userGuide.t2t
Labels: incubating

#8198 Fix Smart Beetle scroll keys
  source/brailleDisplayDrivers/hims.py
Labels: incubating

#8165 Try to use window.edit.Edit when an editable window supports it
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/window/__init__.py
  source/NVDAObjects/window/edit.py
  source/winUser.py
Labels: incubating

#8252 Fix accelerator conflict with apply button.
  source/gui/settingsDialogs.py
Labels: incubating

#8208 Handlers can have required params with extension points.
  sconstruct
  source/extensionPoints.py
  source/extensionPoints/__init__.py
  source/extensionPoints/util.py
  tests/unit/test_extensionPoints.py
Labels: incubating

#8258 Support Win10 rs5 task switch list
  source/appModules/explorer.py
Labels: incubating

#8257 Ignore UIA notification events with no valid NVDAObject
  source/NVDAObjects/__init__.py
  source/_UIAHandler.py
Labels: incubating

#8232 Both sleep before and after closing the connection to a handy tech display
  source/brailleDisplayDrivers/handyTech.py
Labels: incubating

#8316 Fix reading empty columns in Windows Explorer on Windows 7
  source/appModules/explorer.py
Labels: incubating, regression

#8253 Fix currently edited profile announcements, numpad enter functionality and validation behavior
  source/appModules/nvda.py
  source/gui/settingsDialogs.py
Labels: incubating
