Repository nvaccess/nvda, pull requests merged in 2018-08, with the labels that each got.

#7606 Config: add saveConfig and resetConfig actions
  source/audioDucking.py
  source/braille.py
  source/brailleInput.py
  source/config/__init__.py
  source/core.py
  source/synthDriverHandler.py
  user_docs/en/changes.t2t
Labels: incubating

#8479 Get reliable points from offsets in virtual buffers
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  nvdaHelper/vbufBase/storage.cpp
  source/NVDAObjects/IAccessible/__init__.py
  source/virtualBuffers/__init__.py
  source/virtualBuffers/adobeAcrobat.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
Labels: Browse mode, Chrome, Firefox, Text info

#8606 Python 3 imports: try importing Python 3 version before resorting to using Python 2 names
  site_scons/site_tools/doxygen.py
  source/JABHandler.py
  source/NVDAHelper.py
  source/NVDAObjects/inputComposition.py
  source/NVDAObjects/window/akelEdit.py
  source/NVDAObjects/window/excel.py
  source/appModules/digitaleditionspreview.py
  source/appModules/esybraille.py
  source/appModules/hxoutlook.py
  source/appModules/miranda64.py
  source/appModules/mpc-hc.py
  source/appModules/mpc-hc64.py
  source/appModules/sts.py
  source/appModules/teamtalk3.py
  source/appModules/totalcmd64.py
  source/appModules/win32calc.py
  source/appModules/winmail.py
  source/appModules/wlmail.py
  source/appModules/zend-eclipse-php.py
  source/appModules/zendstudio.py
  source/brailleDisplayDrivers/papenmeier.py
  source/config/__init__.py
  source/easeOfAccess.py
  source/extensionPoints/__init__.py
  source/gui/__init__.py
  source/gui/configProfiles.py
  source/gui/settingsDialogs.py
  source/hwPortUtils.py
  source/installer.py
  source/mathType.py
  source/nvda.pyw
  source/queueHandler.py
  source/synthDrivers/_espeak.py
  source/synthDrivers/audiologic.py
  source/synthDrivers/espeak.py
  source/synthDrivers/mssp.py
  source/synthDrivers/oneCore.py
  source/synthDrivers/sapi4.py
  source/synthDrivers/sapi5.py
Labels: Python 3
