Repository nvaccess/nvda, pull requests merged in 2018-06, with the labels that each got.

#8392 Instruct appveyor to build PRs
  appveyor.yml
Labels: incubating

#8280 Expose grammar errors from IAccessible2 text.
  source/NVDAObjects/IAccessible/__init__.py
Labels: Text info, incubating

#8236 added an @script decorator to scriptHandler for setting script metadata
  developerGuide.t2t
  source/NVDAObjects/window/excel.py
  source/baseObject.py
  source/scriptHandler.py
  tests/unit/test_baseObject.py
  tests/unit/test_scriptHandler.py
Labels: incubating

#8181 Update the Audacity appModule
  source/appModules/audacity.py
Labels: incubating

#8143 General Settings/Language: sort items based on descriptions
  source/gui/settingsDialogs.py
  source/languageHandler.py
Labels: incubating

#7387 Add more default task switching gestures to freedom scientific braille displays
  source/brailleDisplayDrivers/freedomScientific.py
  user_docs/en/userGuide.t2t
Labels: incubating, quick fix

#6316 BrailleNote: support for QT and Apex BT scroll wheel
  source/brailleDisplayDrivers/brailleNote.py
  user_docs/en/userGuide.t2t
Labels: incubating

#8217 Send current synthDriver name and brailleDisplay name to update server for stats gathering.
  source/config/configSpec.py
  source/core.py
  source/gui/__init__.py
  source/gui/settingsDialogs.py
  source/logHandler.py
  source/updateCheck.py
  user_docs/en/userGuide.t2t
Labels: incubating

#6607 Add scripts for reporting elapsed and total time of current track in Foobar2000
  source/appModules/foobar2000.py
  user_docs/en/userGuide.t2t
Labels: incubating

#8382 NvDA/AppX: do not present 'restart with add-ons disabled' in exit dialog as this edition does not support add-ons yet
  appx/manifest.xml.subst
  source/gui/__init__.py
Labels: incubating

#8366 Add the Mac command key unicode character to symbols.dic.
  source/locale/en/symbols.dic
Labels: incubating

#8352 Report author-provided accessible labels in Chrome that are not visible elsewhere on the page
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.h
Labels: incubating

#8346 Support aria-roledescription.
  nvdaHelper/vbufBackends/mshtml/mshtml.cpp
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/speech.py
  source/textInfos/__init__.py
  source/virtualBuffers/MSHTML.py
  source/virtualBuffers/gecko_ia2.py
Labels: incubating

#8227 Add Swedish 8 dot computer braille table
  source/brailleTables.py
Labels: Braille, incubating, quick fix

#6078 Object coordinates: It is now possible to hear object coordinates when using object navigation commands. re #2559
  source/NVDAObjects/__init__.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/mouseHandler.py
  source/screenExplorer.py
  user_docs/en/userGuide.t2t
Labels: blocked
