Repository nvaccess/nvda, pull requests merged in 2019-05, with the labels that each got.

#9497 Added shift+enter and shift+numpadEnter keys to announce the reverse located cell in the same column in Excel
  source/NVDAObjects/window/excel.py
Labels: quick fix

#9057 Add mouse text resolution input gesture
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/textInfos/__init__.py
  user_docs/en/userGuide.t2t
Labels: AfterPython3Transition, Mouse tracking

#9334 Perform lower case comparison of add-on names when updating, and make sure not to remove the previous add-on when the current add-on fails installation
  source/gui/addonGui.py
Labels: Add-on management, quick fix

#9557 Quick fix for PR #9415 (missed a little change)
  source/appModules/devenv.py
Labels: regression

#7599 New speech framework including callbacks, beeps, sounds, profile switches and prioritized queuing
  source/NVDAObjects/IAccessible/__init__.py
  source/config/__init__.py
  source/nvwave.py
  source/sayAllHandler.py
  source/speech.py
  source/synthDriverHandler.py
  source/synthDrivers/_audiologic.py
  source/synthDrivers/_espeak.py
  source/synthDrivers/audiologic.py
  source/synthDrivers/espeak.py
  source/synthDrivers/oneCore.py
  source/synthDrivers/sapi4.py
  source/synthDrivers/sapi5.py
  tests/system/libraries/speechSpy.py
  tests/unit/__init__.py
Labels: Speech, Speech synth drivers

#8214 Allow setting braille display specific settings in the GUI
  source/braille.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/eurobraille.py
  source/brailleDisplayDrivers/handyTech.py
  source/config/configSpec.py
  source/driverHandler.py
  source/gui/guiHelper.py
  source/gui/nvdaControls.py
  source/gui/settingsDialogs.py
  source/speechDictHandler/__init__.py
  source/synthDriverHandler.py
  source/synthDrivers/espeak.py
  source/synthDrivers/oneCore.py
  source/synthSettingsRing.py
Labels: NVDA GUI, Speech synth drivers

#9587 Fix overlooked rename of ID to id in synthDriverHandler.LanguageInfo
  source/synthDriverHandler.py
Labels: p1, regression
