Repository nvaccess/nvda, pull requests merged in 2019-06, with the labels that each got.

#8647 nvwave.playWaveFile: async > asynchronous
  source/core.py
  source/nvwave.py
  source/speech/commands.py
Labels: Python 3, quick fix

#9664 Python 3: print statement -> print function
  source/appModuleHandler.py
  source/synthDrivers/sapi5.py
Labels: Python 3

#9605 Update setup script for Python 3.7
  source/logHandler.py
  source/setup.py
Labels: Python 3, threshold

#9690 Add NVDA+F1 shortcut to the userguide
  user_docs/en/userGuide.t2t
Labels: Documentation

#9774 Python 3: fix several remaining division errors
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/behaviors.py
  source/NVDAObjects/window/edit.py
  source/api.py
  source/appModules/devenv.py
  source/appModules/nlnotes.py
  source/displayModel.py
  source/touchHandler.py
  source/touchTracker.py
  source/virtualBuffers/adobeFlash.py
  source/virtualBuffers/gecko_ia2.py
  source/virtualBuffers/lotusNotes.py
  source/virtualBuffers/webKit.py
  source/winConsoleHandler.py
Labels: Python 3
