Repository nvaccess/nvda, pull requests merged in 2020-04, with the labels that each got.

#10784 Add support for Windows Terminal
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/UIA/winConsoleUIA.py
  source/NVDAObjects/behaviors.py
  user_docs/en/userGuide.t2t
Labels: app/windows-terminal, enhancement

#10746 Remove old plugins directories when initializing config.
  source/config/__init__.py
Labels: enhancement

#9325 add reportActiveConfigurationProfile command
  source/globalCommands.py
Labels: feature

#10976 Settings/object presentation: fix accelerator for 'guess object position information' checkbox
  source/gui/settingsDialogs.py
Labels: bug

#10553 System tests with HTML samples.
  tests/system/NVDA Core/startupShutdownNVDA.robot
  tests/system/NVDA Core/variables.py
  tests/system/libraries/AssertsLib.py
  tests/system/libraries/ChromeLib.py
  tests/system/libraries/KeyInputLib.py
  tests/system/libraries/NvdaLib.py
  tests/system/libraries/SystemTestSpy/__init__.py
  tests/system/libraries/SystemTestSpy/blockUntilConditionMet.py
  tests/system/libraries/SystemTestSpy/configManager.py
  tests/system/libraries/SystemTestSpy/getLib.py
  tests/system/libraries/SystemTestSpy/speechSpyGlobalPlugin.py
  tests/system/libraries/SystemTestSpy/speechSpySynthDriver.py
  tests/system/libraries/helperLib.py
  tests/system/libraries/nvdaRobotLib.py
  tests/system/libraries/speechSpy.py
  tests/system/libraries/systemTestSpy.py
  tests/system/nvdaSettingsFiles/standard-doShowWelcomeDialog.ini
  tests/system/nvdaSettingsFiles/standard-dontShowWelcomeDialog.ini
  tests/system/readme.md
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  tests/system/robot/startupShutdownNVDA.py
  tests/system/robot/startupShutdownNVDA.robot
Labels: feature

#10979 Fix superscripts and subscripts reporting for MS Word (legacy).
  nvdaHelper/remote/winword.cpp
  source/NVDAObjects/window/winword.py
Labels: app/microsoft-office, enhancement

#10934 Split IAccessible handler and Add tests for OrderedWinEventLimiter
  source/IAccessibleHandler.py
  source/IAccessibleHandler/__init__.py
  source/IAccessibleHandler/internalWinEventHandler.py
  source/IAccessibleHandler/orderedWinEventLimiter.py
  source/NVDAObjects/UIA/winConsoleUIA.py
  source/NVDAObjects/window/winConsole.py
  tests/unit/test_orderedWinEventLimiter.py
Labels: feature

#10977 Python syntax: replace identity comparison (var is/is not literal) with equality comparison (var ==/!= literal)
  source/browseMode.py
  source/buildVersion.py
  source/virtualBuffers/gecko_ia2.py
Labels: maintenance

#11017 Fix a rare infinite loop in IAccessibleHandler.findGroupboxObject.
  source/IAccessibleHandler/__init__.py
Labels: bug

#11040 Stronger guarantee regarding Generators in speech
  source/sayAllHandler.py
  source/speech/__init__.py
  source/speech/types.py
Labels: Addon/API, bug, component/speech

#11050 Don't attempt to format a tuple with "%s"
  source/NVDAObjects/IAccessible/MSHTML.py
Labels: bug, p2

#11049 Refactor for cancellable speech
  source/speech/__init__.py
  source/speech/manager.py
  source/synthDriverHandler.py
Labels: deprecated/2021.1

#11054 Temporarily disable the Chrome system tests.
  appveyor.yml
  readme.md
  tests/system/readme.md
  tests/system/robot/chromeTests.robot
  tests/system/robot/startupShutdownNVDA.robot
  tests/system/robotArgs.robot
  tests/system/sconscript
Labels: bug, system-test

#10941 Adjust wording of sign-in text
  source/gui/__init__.py
  source/gui/installerGui.py
  source/gui/settingsDialogs.py
  user_docs/en/userGuide.t2t
Labels: bug

#9792 AppModule: Customize retrieval of status bar object or TextInfo (#4640)
  source/api.py
  source/appModuleHandler.py
  source/globalCommands.py
Labels: Addon/API, enhancement

#10921 Revert appModule for VS Code to disable browse mode by default
  source/appModules/code.py
Labels: app/vs-code, maintenance

#11072 eventHandler: Drop hide events.
  source/eventHandler.py
Labels: bug, performance
