Repository nvaccess/nvda, pull requests merged in 2020-08, with the labels that each got.

#11402 I6060 add emulated kb gesture support
  source/gui/__init__.py
  source/gui/guiHelper.py
  source/gui/inputGestures.py
  source/gui/settingsDialogs.py
  source/inputCore.py
  source/keyboardHandler.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: component/NVDA-GUI, feature/input-gestures

#9911 Browseable Messages - Centered and enlarged (#9910)
  source/ui.py
  user_docs/en/changes.t2t
Labels: audience/low-vision, component/NVDA-GUI, enhancement, ux

#9844 Support copying a fragment of the log to the clipboard (#9280)
  source/globalCommands.py
  source/logHandler.py
  user_docs/en/changes.t2t
Labels: component/logging, feature

#11024 nvwave: Don't close the audio device unless there hasn't been any audio played for 10 seconds.
  source/nvwave.py
  user_docs/en/changes.t2t
Labels: bug, component/audio
