Repository nvaccess/nvda, pull requests merged in 2020-05, with the labels that each got.

#10981 No longer access MS Office ribbons, status bars and context menus via UIA for Office <= 2013
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/IAccessible/msOffice.py
  source/_UIAHandler.py
Labels: app/microsoft-office, bug

#11075 Gecko vbuf backend: Treat display: inline-flex as inline, not block.
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
Labels: app/chrome, app/firefox, feature/browse-mode, maintenance

#11099 Flake8: Also check `*.pyw` and `sconscript` (#11097)
  tests/lint/flake8.ini
Labels: maintenance

#11095 Fix Powerpoint: reportSuperscriptAndSubscript error
  source/appModules/powerpnt.py
Labels: bug, bug/regression

#11091 Fix broken link to the wiki regarding translating NVDA
  devDocs/developerGuide.t2t
Labels: component/documentation, component/i18n

#11081 Set `xgettext` encoding to UTF-8 (#11080)
  sconstruct
Labels: maintenance

#11093 Fix missing translator comment warning for split translatable strings
  source/globalCommands.py
  source/gui/__init__.py
  source/gui/addonGui.py
  source/gui/installerGui.py
  source/gui/settingsDialogs.py
  source/updateCheck.py
  source/versionInfo.py
  tests/checkPot.py
Labels: component/i18n, maintenance

#11119 Userdocs: clarify whole word radio for speech dictionaries
  user_docs/en/userGuide.t2t
Labels: component/documentation

#10885 Cancellable speech
  source/NVDAObjects/__init__.py
  source/config/configSpec.py
  source/eventHandler.py
  source/gui/settingsDialogs.py
  source/speech/__init__.py
  source/speech/commands.py
  source/speech/manager.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: feature

#11076 Cleanup: Stop listening for IAccessible reorder events.
  source/IAccessibleHandler/internalWinEventHandler.py
  source/eventHandler.py
Labels: maintenance

#10918 Don't use UIATextInfo for DevExpress UIA Elements with Text Pattern without Document range
  source/NVDAObjects/UIA/__init__.py
Labels: bug
