Repository nvaccess/nvda, pull requests merged in 2020-11, with the labels that each got.

#11826 Chrome system tests - off by one error
  tests/system/libraries/ChromeLib.py
Labels: component/system-testing

#9679 Add --copy-portable-config command line parameter to automatically copy the portable configuration with a silent installation
  source/core.py
  source/gui/installerGui.py
  source/nvda.pyw
  user_docs/en/userGuide.t2t
Labels: Abandoned, BabbageWork, feature

#9079 Refactor NVDAHelper32remote Live region handler
  nvdaHelper/interfaces/nvdaControllerInternal/nvdaControllerInternal.acf
  nvdaHelper/interfaces/nvdaControllerInternal/nvdaControllerInternal.idl
  nvdaHelper/local/nvdaControllerInternal.c
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/remote/ia2LiveRegions.cpp
  nvdaHelper/remote/nvdaHelperRemote.def
  nvdaHelper/vbufBackends/mshtml/node.cpp
  nvdaHelper/vbufBackends/mshtml/node.h
  source/NVDAHelper.py
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/UIA/__init__.py
  source/_UIAHandler.py
  source/aria.py
  user_docs/en/changes.t2t
Labels: feature

#9843 Uniformize all "Copied to clipboard" messages (#6757)
  source/api.py
  source/cursorManager.py
  source/globalCommands.py
  source/textInfos/__init__.py
  source/treeInterceptorHandler.py
  source/ui.py
  user_docs/en/changes.t2t
Labels: enhancement

#11804 Add braille viewer braille routing
  source/braille.py
  source/brailleViewer/__init__.py
  source/brailleViewer/brailleViewerGui.py
  source/brailleViewer/brailleViewerInputGesture.py
  source/config/configSpec.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: audience/a11y-tester, audience/nvda-dev, component/braille

#10048 Improve presentation of graphical view table in disk management
  source/appModules/mmc.py
  user_docs/en/changes.t2t
Labels: enhancement

#9429 Windows 10 Calculator: resolve expression entry repetitions
  source/appModules/calculator.py
  user_docs/en/changes.t2t
Labels: app/windows-interface, feature, ux
