Repository nvaccess/nvda, pull requests merged in 2020-09, with the labels that each got.

#11577 Prepare changes file for 2020.4
  source/buildVersion.py
  user_docs/en/changes.t2t
Labels: maintenance/releaseProcess

#11578 Add 2020.3 blurb
  user_docs/en/changes.t2t
Labels: maintenance/releaseProcess

#11456 I7757 context help
  source/browseMode.py
  source/gui/__init__.py
  source/gui/addonGui.py
  source/gui/configProfiles.py
  source/gui/contextHelp.py
  source/gui/inputGestures.py
  source/gui/settingsDialogs.py
  source/speechViewer.py
  source/updateCheck.py
  user_docs/en/changes.t2t
Labels: component/documentation, ux

#10387 Visual Studio: fix bugs in object model implementation, majorly stripping down the appModule
  source/appModules/devenv.py
Labels: maintenance

#11592 Include latest changes from beta
  source/NVDAObjects/window/edit.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/keyboardHandler.py
  source/locale/hr/LC_MESSAGES/nvda.po
  source/locale/it/LC_MESSAGES/nvda.po
  source/locale/ru/LC_MESSAGES/nvda.po
  source/locale/sr/LC_MESSAGES/nvda.po
  source/locale/tr/LC_MESSAGES/nvda.po
  source/locale/uk/LC_MESSAGES/nvda.po
  source/locale/vi/LC_MESSAGES/nvda.po
  source/locale/zh_CN/LC_MESSAGES/nvda.po
  source/nvwave.py
  user_docs/en/changes.t2t
  user_docs/fa/userGuide.t2t
  user_docs/fr/changes.t2t
  user_docs/hr/changes.t2t
  user_docs/hr/userGuide.t2t
  user_docs/ja/userGuide.t2t
  user_docs/nl/userGuide.t2t
  user_docs/ro/changes.t2t
  user_docs/ta/userGuide.t2t
  user_docs/tr/changes.t2t
  user_docs/tr/userGuide.t2t
  user_docs/vi/changes.t2t
  user_docs/vi/userGuide.t2t
Labels: maintenance/releaseProcess

#10567 When Windows 7 start menu closes and focus lands on a WorkerW pane redirect focus to the focused Desktop item.
  source/appModules/explorer.py
  user_docs/en/changes.t2t
Labels: app/windows-interface, enhancement

#11633 Fix typo in changelog
  user_docs/en/changes.t2t
Labels: component/documentation

#11656 Merge beta to master
  source/appModules/code - insiders.py
  source/appModules/code.py
  source/brailleDisplayDrivers/handyTech.py
  source/gui/settingsDialogs.py
  source/locale/ar/LC_MESSAGES/nvda.po
  source/locale/da/LC_MESSAGES/nvda.po
  source/locale/de/LC_MESSAGES/nvda.po
  source/locale/es/LC_MESSAGES/nvda.po
  source/locale/fi/LC_MESSAGES/nvda.po
  source/locale/fr/LC_MESSAGES/nvda.po
  source/locale/gl/LC_MESSAGES/nvda.po
  source/locale/it/LC_MESSAGES/nvda.po
  source/locale/ja/LC_MESSAGES/nvda.po
  source/locale/nl/LC_MESSAGES/nvda.po
  source/locale/pt_BR/LC_MESSAGES/nvda.po
  source/locale/ro/LC_MESSAGES/nvda.po
  source/locale/ru/LC_MESSAGES/nvda.po
  source/locale/ta/LC_MESSAGES/nvda.po
  source/locale/zh_CN/LC_MESSAGES/nvda.po
  source/locale/zh_CN/symbols.dic
  source/nvwave.py
  source/synthDrivers/sapi5.py
  user_docs/ar/changes.t2t
  user_docs/da/changes.t2t
  user_docs/da/userGuide.t2t
  user_docs/de/changes.t2t
  user_docs/de/userGuide.t2t
  user_docs/en/changes.t2t
  user_docs/es/changes.t2t
  user_docs/es/userGuide.t2t
  user_docs/fi/changes.t2t
  user_docs/fi/userGuide.t2t
  user_docs/fr/changes.t2t
  user_docs/fr/userGuide.t2t
  user_docs/gl/changes.t2t
  user_docs/gl/userGuide.t2t
  user_docs/hr/changes.t2t
  user_docs/ja/userGuide.t2t
  user_docs/ko/userGuide.t2t
  user_docs/nl/changes.t2t
  user_docs/pl/changes.t2t
  user_docs/ro/changes.t2t
  user_docs/sr/changes.t2t
  user_docs/sr/userGuide.t2t
  user_docs/ta/userGuide.t2t
  user_docs/tr/changes.t2t
  user_docs/vi/changes.t2t
  user_docs/zh_CN/userGuide.t2t
  user_docs/zh_TW/userGuide.t2t
Labels: maintenance/releaseProcess

#11701 Revert PR #11586
  source/synthDrivers/sapi5.py
  user_docs/en/changes.t2t
Labels: maintenance/releaseProcess

#11703 Merge beta into master
  source/browseMode.py
  source/locale/an/LC_MESSAGES/nvda.po
  source/locale/de/LC_MESSAGES/nvda.po
  source/locale/es_CO/LC_MESSAGES/nvda.po
  source/locale/fi/LC_MESSAGES/nvda.po
  source/locale/fr/LC_MESSAGES/nvda.po
  source/locale/hr/LC_MESSAGES/nvda.po
  source/locale/ja/LC_MESSAGES/nvda.po
  source/locale/ko/LC_MESSAGES/nvda.po
  source/locale/nl/LC_MESSAGES/nvda.po
  source/locale/pl/LC_MESSAGES/nvda.po
  source/locale/pt_BR/LC_MESSAGES/nvda.po
  source/locale/pt_PT/LC_MESSAGES/nvda.po
  source/locale/ro/LC_MESSAGES/nvda.po
  source/locale/ta/LC_MESSAGES/nvda.po
  source/locale/tr/LC_MESSAGES/nvda.po
  source/locale/vi/LC_MESSAGES/nvda.po
  source/locale/zh_TW/LC_MESSAGES/nvda.po
  source/synthDrivers/sapi5.py
  user_docs/en/changes.t2t
  user_docs/ko/changes.t2t
  user_docs/pl/changes.t2t
  user_docs/pl/userGuide.t2t
  user_docs/pt_PT/changes.t2t
  user_docs/pt_PT/userGuide.t2t
  user_docs/ta/userGuide.t2t
  user_docs/uk/userGuide.t2t
Labels: maintenance/releaseProcess
