Repository nvaccess/nvda, pull requests merged in 2020-03, with the labels that each got.

#10875 Catch exceptions when creating shortcuts
  source/installer.py
Labels: bug, component/installer

#10878 sayAll skim reading no longer keeps announcing exiting initial control fields
  source/sayAllHandler.py
  source/speech/__init__.py
Labels: deprecated/2021.1

#10802 Fix of error preventing start when log unavailable
  source/gui/logViewer.py
  source/logHandler.py
Labels: bug, component/logging

#10493 Add a script to oopen NVDA config directory
  source/config/__init__.py
  source/globalCommands.py
  source/gui/__init__.py
  source/gui/installerGui.py
  source/nvda_slave.pyw
  source/systemUtils.py
  user_docs/en/userGuide.t2t
Labels: deprecated/2021.1, feature

#10894 Add appModule for ESET antivirus gui.
  source/appModules/egui.py
Labels: enhancement
