Repository nvaccess/nvda, pull requests merged in 2020-07, with the labels that each got.

#11318 Fix pop error on empty list
  source/NVDAObjects/IAccessible/ia2TextMozilla.py
Labels: bug

#10355 Sort languages list in general settings
  source/languageHandler.py
  user_docs/en/changes.t2t
Labels: enhancement, p3

#10159 GUI: Standard dialog separated dismiss buttons and borders (#6468)
  source/gui/__init__.py
  source/gui/addonGui.py
  source/gui/configProfiles.py
  source/gui/guiHelper.py
  source/gui/installerGui.py
  source/gui/settingsDialogs.py
Labels: component/NVDA-GUI, enhancement, ux

#10307 Input Gestures dialog: Async filtering for smoother response
  source/gui/settingsDialogs.py
Labels: component/NVDA-GUI, enhancement, ux

#10796 `brailleInput.handler.sendChars`: allow sending Unicode characters beyond U+FFFF
  source/brailleInput.py
Labels: component/braille, feature

#11214 Selective UIA event handling
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/behaviors.py
  source/UIAUtils.py
  source/_UIAHandler.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/userGuide.t2t
Labels: api/uia, performance

#8644 App modules: add additional app properties such as app path, immersive process, and app architecture
  source/appModuleHandler.py
Labels: Addon/API, audience/nvda-dev, enhancement

#8858 Improve presentation of checkable list items
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/behaviors.py
  source/controlTypes.py
  tests/unit/test_controlTypes.py
Labels: enhancement

#9119 App modules/WWAHost: use package functions to determine product name/version and which app module to load
  devDocs/developerGuide.t2t
  source/appModules/wwahost.py
Labels: Addon/API, audience/nvda-dev, enhancement

#11268 Adds new German braille tables
  source/brailleTables.py
  user_docs/en/changes.t2t
Labels: component/braille, component/liblouis

#10087 Add-Ons Manager: Change default Button to "No" for Delete Add-On Confirmation Dialog (#10015)
  source/gui/addonGui.py
Labels: enhancement, ux

#11329 Excel - Element List dialog: Present the localized version of formulas (#9144)
  nvdaHelper/remote/excel.cpp
  nvdaHelper/remote/excel/Constants.h
  source/NVDAObjects/window/excel.py
Labels: app/microsoft-office, feature/i18n

#11346 I8438 fix ordered list start number in ie
  nvdaHelper/vbufBackends/mshtml/mshtml.cpp
  user_docs/en/changes.t2t
Labels: app/internet-explorer, bug

#10494 Read-only states for UIA objects
  source/NVDAObjects/UIA/__init__.py
  source/appModules/outlook.py
  user_docs/en/changes.t2t
Labels: enhancement

#11412 Try f6 and no auto say all for chrome system tests
  tests/system/libraries/ChromeLib.py
  tests/system/nvdaSettingsFiles/standard-doShowWelcomeDialog.ini
  tests/system/nvdaSettingsFiles/standard-dontShowWelcomeDialog.ini
Labels: component/system-testing

#11433 Don't fail build when symbols can't be uploaded
  appveyor.yml
  appveyor/mozillaSyms.py
Labels: component/build

#10723 Fix say all error when on Desktop
  source/sayAllHandler.py
Labels: bug
