Repository nvaccess/nvda, pull requests merged in 2020-06, with the labels that each got.

#11195 Updated readme with a new section "getting support" and converted the ControllerClient Readme to show up properly on Github
  extras/controllerClient/readme.html
  extras/controllerClient/readme.md
  readme.md
Labels: component/documentation

#9553 Review cursor: don't report "top"/"bottom" message when moving on the first/last line of the current object
  source/globalCommands.py
  user_docs/en/changes.t2t
Labels: component/audio-ux, feature, ux

#10922 Introduce support for Windows 10 Version 2004 (May 2020 Update/build 19041)
  readme.md
  source/comInterfaces/_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py
  source/winVersion.py
Labels: maintenance

#11245 Fix several issues in speech manager
  source/eventHandler.py
  source/speech/commands.py
  source/speech/manager.py
  source/speech/types.py
  tests/unit/test_speechManager/__init__.py
  tests/unit/test_speechManager/speechManagerTestHarness.py
Labels: component/speech, component/unit-testing

#11226 Added clarification that ctrl+enter activates the element containing formula in Math content
  user_docs/en/userGuide.t2t
Labels: component/documentation, feature/math

#10877 Rewording in Input Gestures
  source/globalCommands.py
Labels: bug

#11280 Adds Ukrainian computer braille table
  source/brailleTables.py
Labels: component/braille, component/liblouis

#10973 Add a command to check formatting for the text under the caret.
  source/globalCommands.py
  user_docs/en/userGuide.t2t
Labels: feature, feature/input-gestures

#10889 Use FullDescription for UIA
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/UIA/edge.py
Labels: bug

#11264 Changes file fixes
  user_docs/en/changes.t2t
Labels: component/documentation

#9355 Allow toggling reporting of graphics
  nvdaHelper/remote/winword.cpp
  source/NVDAObjects/UIA/wordDocument.py
  source/NVDAObjects/window/winword.py
  source/braille.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/speech/__init__.py
  source/textInfos/__init__.py
  user_docs/en/userGuide.t2t
Labels: feature

#10557 Touch interaction: allow users to disable touch support completely
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/touchHandler.py
  user_docs/en/userGuide.t2t
Labels: feature

#11316 Restore chrome system tests
  tests/system/libraries/ChromeLib.py
  tests/system/libraries/NvdaLib.py
  tests/system/libraries/SystemTestSpy/blockUntilConditionMet.py
  tests/system/libraries/SystemTestSpy/speechSpyGlobalPlugin.py
  tests/system/requirements.txt
  tests/system/robot/chromeTests.robot
  tests/system/robot/startupShutdownNVDA.robot
  tests/system/sconscript
Labels: component/system-testing
