Repository nvaccess/nvda, pull requests merged in 2021-02, with the labels that each got.

#11782 Fix misleading log message for aria-current="true"
  source/NVDAObjects/IAccessible/MSHTML.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/UIA/edge.py
  source/NVDAObjects/__init__.py
  source/braille.py
  source/controlTypes.py
  source/speech/__init__.py
  source/virtualBuffers/MSHTML.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12027 add styles for userguide and changes
  .gitignore
  sconstruct
  user_docs/en/changes.t2t
  user_docs/global.t2tconf
  user_docs/styles.css
Labels: component/documentation

#9631 Report comments in MS Word with UIA enabled
  source/NVDAObjects/UIA/wordDocument.py
  user_docs/en/changes.t2t
Labels: app/microsoft-office, feature

#12020 Python 3.8/liblouis helper: add NVDA executable path by calling os.add_dll_directory
  source/louisHelper.py
Labels: Python 3.8

#12083 Fix command line length limit reached
  sconstruct
Labels: maintenance

#10795 Report 'unsupported' when toggling screen layout in Word
  source/browseMode.py
  source/virtualBuffers/__init__.py
  user_docs/en/changes.t2t
Labels: bug
