Repository nvaccess/nvda, pull requests merged in 2021-07, with the labels that each got.

#11856 Speak all symbols when moving by words (#11779)
  source/characterProcessing.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/speech/speech.py
  tests/system/libraries/NotepadLib.py
  tests/system/nvdaSettingsFiles/symbolLevelWordOff.ini
  tests/system/robot/notepadTests.py
  tests/system/robot/notepadTests.robot
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: deprecated/2022.1

#10349 appModules/SearchUI: add support for announcing suggestion count in Windows 10 Version 1909 and later
  source/appModules/searchui.py
  user_docs/en/changes.t2t
Labels: app/windows-interface, enhancement

#10415 Vocalize paragraph indent and hanging indent shortcuts in MS Word
  source/NVDAObjects/window/winword.py
  user_docs/en/changes.t2t
Labels: app/microsoft-office, feature

#10408 Add toggleReportCellBorders script to input gestures.
  source/globalCommands.py
  user_docs/en/changes.t2t
Labels: app/microsoft-office, feature

#12658 Expose transparent background colors for displayModel
  devDocs/displayModel.md
  nvdaHelper/remote/displayModel.cpp
  nvdaHelper/remote/displayModel.h
  nvdaHelper/remote/gdiHooks.cpp
  nvdaHelper/remote/gdiHooks.h
  source/colors.py
  source/config/configSpec.py
  source/displayModel.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: component/display-model
