Repository nvaccess/nvda, pull requests merged in 2021-03, with the labels that each got.

#12111 Fix typo's in the issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: maintenance

#12139 remove winKernel.GetTimeFormat, winKernel.GetDateFormat and usages
  source/appModules/outlook.py
  source/winKernel.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12144 remove DriverSettingsMixin alias for AutoSettingsMixin
  source/gui/settingsDialogs.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12145 remove getSpeechForSpelling alias for getSpellingSpeech
  source/speech/__init__.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12126 Deprecate import of Commands directly from speech module in favour of speech.commands
  source/mathPres/__init__.py
  source/mathPres/mathPlayer.py
  source/sayAllHandler.py
  source/speech/__init__.py
  source/speech/manager.py
  source/speechXml.py
  source/synthDriverHandler.py
  source/synthDrivers/espeak.py
  source/synthDrivers/oneCore.py
  source/synthDrivers/sapi4.py
  source/synthDrivers/sapi5.py
  source/synthDrivers/silence.py
  tests/system/libraries/SystemTestSpy/speechSpySynthDriver.py
  tests/unit/test_speechManager/__init__.py
  tests/unit/test_speechManager/speechManagerTestHarness.py
  tests/unit/test_speechXml.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12150 implement deprecation of SAYALL behaviour for speakTextInfo
  source/speech/__init__.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12164 controlTypes: Remove deprecated ROLE_EQUATION
  source/controlTypes.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12172 don't rely on star imports from synthDriverHandler
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/sayAllHandler.py
  source/synthDriverHandler.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12168 Use DriverSetting classes from autoSettingUtils rather than from driverHandler
  source/braille.py
  source/driverHandler.py
  source/synthDriverHandler.py
  source/synthDrivers/espeak.py
  source/synthSettingsRing.py
  source/visionEnhancementProviders/NVDAHighlighter.py
  source/visionEnhancementProviders/_exampleProvider_autoGui.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12157 TextInfos must inherit from BaseContentRecogTextInfo
  source/contentRecog/recogUi.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#11266 Enable cancellable speech by default
  source/gui/settingsDialogs.py
  source/speech/manager.py
  user_docs/en/changes.t2t
Labels: blocked

#12195 Remove backwards compat aliases from PR 10593
  source/sayAllHandler.py
  source/speech/__init__.py
  tests/unit/test_SpeechWithoutPauses.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12105 Move some classes from the main gui module.
  source/core.py
  source/documentationUtils.py
  source/gui/__init__.py
  source/gui/contextHelp.py
  source/gui/startupDialogs.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12208 Fix routing to cell in selection (braille)
  source/braille.py
Labels: component/braille

#11909 Introduce winVersion.WinVersion class to record Windows version information, removing winVersion.isWin10 function
  source/COMRegistrationFixes/__init__.py
  source/NVDAObjects/IAccessible/winConsole.py
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/UIA/spartanEdge.py
  source/_UIAHandler.py
  source/appModuleHandler.py
  source/appModules/explorer.py
  source/appModules/putty.py
  source/appModules/windowsinternal_composableshell_experiences_textinput_inputapp.py
  source/core.py
  source/easeOfAccess.py
  source/gui/settingsDialogs.py
  source/keyboardHandler.py
  source/synthDriverHandler.py
  source/synthDrivers/oneCore.py
  source/touchHandler.py
  source/updateCheck.py
  source/winVersion.py
  tests/unit/test_winVersion.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#12232 Remove backwards compat code from IAccessibleHandler
  source/IAccessibleHandler/__init__.py
  source/IAccessibleHandler/internalWinEventHandler.py
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/IAccessible/chromium.py
  source/NVDAObjects/IAccessible/ia2TextMozilla.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/IAccessible/mozilla.py
  source/NVDAObjects/window/edit.py
  source/NVDAObjects/window/scintilla.py
  source/appModules/kindle.py
  source/appModules/soffice.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
Labels: deprecated/2021.1

#11598 Report appointment categories in Microsoft Outlook
  source/appModules/outlook.py
  source/languageHandler.py
  user_docs/en/changes.t2t
Labels: app/microsoft-office
