Repository nvaccess/nvda, pull requests merged in 2022-08, with the labels that each got.

#13911 Change format of add/remove programs registration to improve winget support
  source/buildVersion.py
  source/installer.py
  source/versionInfo.py
  user_docs/en/changes.t2t
Labels: merge-early

#13297 Prepare for selective UIA event registration by default
  source/UIAHandler/__init__.py
  source/UIAHandler/utils.py
  source/config/configSpec.py
  source/config/profileUpgradeSteps.py
  source/gui/settingsDialogs.py
  user_docs/en/userGuide.t2t
Labels: blocked/needs-code-review, merge-early

#14021 Add new scripts to move review cursor by page
  source/globalCommands.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: merge-early

#14019 Send architecture when update checking
  source/updateCheck.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#13989 Split up scriptHandler.findScript
  source/braille.py
  source/inputCore.py
  source/scriptHandler.py
Labels: audience/nvda-dev, merge-early

#14070 Re-Introduce Table SayAll commands
  source/documentBase.py
  source/speech/sayAll.py
  source/virtualBuffers/__init__.py
  source/virtualBuffers/gecko_ia2.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: merge-early

#14024 Ensure indeterminate progress dialogs centred on screen before visible
  source/gui/__init__.py
Labels: merge-early

#14050 Mark globalVars for deprecation
  source/NVDAHelper.py
  source/appModuleHandler.py
  source/appModules/lockapp.py
  source/config/__init__.py
  source/core.py
  source/diffHandler.py
  source/documentationUtils.py
  source/easeOfAccess.py
  source/eventHandler.py
  source/globalVars.py
  source/gui/__init__.py
  source/logHandler.py
  source/nvda.pyw
  source/nvda_slave.pyw
  source/review.py
Labels: release/blocking

#13254 Use modern DPI awareness settings
  source/core.py
  source/manifest.template.xml
  source/setup.py
  source/winAPI/constants.py
  source/winAPI/dpiAwareness.py
  user_docs/en/changes.t2t
Labels: displayScaling, audience/low-vision, conceptApproved, merge-early

#14035 Move MessageWindow from core to winAPI module
  source/NVDAObjects/behaviors.py
  source/bdDetect.py
  source/core.py
  source/globalCommands.py
  source/mouseHandler.py
  source/visionEnhancementProviders/NVDAHighlighter.py
  source/winAPI/_displayTracking.py
  source/winAPI/_powerTracking.py
  source/winAPI/messageWindow.py
  source/winAPI/sessionTracking.py
  source/winAPI/types.py
  source/winAPI/winUser/__init__.py
  source/winAPI/winUser/constants.py
  source/winGDI.py
  source/winInputHook.py
  source/winKernel.py
  source/winUser.py
  source/winVersion.py
  source/windowUtils.py
  tests/unit/test_winAPI/__init__.py
  tests/unit/test_winAPI/test_displayTracking.py
  tests/unit/test_winAPI/test_powerTracking.py
  user_docs/en/changes.t2t
Labels: merge-early
