Repository nvaccess/nvda, pull requests merged in 2022-06, with the labels that each got.

#13439 Remove redundant "-:NOREFS" from SymStore cli options
  appveyor/scripts/buildSymbolStore.ps1
Labels: conceptApproved

#13048 Allow opt out of venv recreation when requirements have changed
  venvUtils/ensureVenv.py
Labels: conceptApproved

#13794 Further change log fixes for 2022.2
  user_docs/en/changes.t2t
Labels: release/blocking

#12843 Excel with UIA: announce merged cells
  source/NVDAObjects/UIA/excel.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#13649 Report ARIA details role
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.h
  nvdaHelper/vbufBase/storage.cpp
  nvdaHelper/vbufBase/storage.h
  readme.md
  source/IAccessibleHandler/__init__.py
  source/NVDAObjects/IAccessible/chromium.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/IAccessible/mozilla.py
  source/NVDAObjects/__init__.py
  source/aria.py
  source/braille.py
  source/compoundDocuments.py
  source/controlTypes/role.py
  source/controlTypes/state.py
  source/speech/speech.py
  source/virtualBuffers/gecko_ia2.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  tests/unit/test_controlTypes.py
  user_docs/en/changes.t2t
Labels: merge-early

#13233 soffice: Make selected cell announcement more efficient
  source/appModules/soffice.py
  user_docs/en/changes.t2t
Labels: app/open-office, conceptApproved, merge-early

#13853 Use importlib.util.find_spec when checking if the given appModule exists to workaround issues in find_module and for forward compatibility.
  source/appModuleHandler.py
Labels: merge-early
