Repository nvaccess/nvda, pull requests merged in 2022-07, with the labels that each got.

#13032 Fallback to UIA if supported in Chromium and we don't have access to IA2
  source/UIAHandler/__init__.py
  source/appModuleHandler.py
  source/systemUtils.py
  user_docs/en/changes.t2t
Labels: blocked/needs-code-review, conceptApproved, merge-early

#13670 Introducing table sayall commands
  source/documentBase.py
  source/speech/sayAll.py
  source/virtualBuffers/__init__.py
  source/virtualBuffers/gecko_ia2.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#13559 Skype for Business: Remove excessive error logging.
  source/appModules/lync.py
Labels: blocked/needs-code-review

#13131 Add an option to prevent speech being interrupted while scrolling the braille display
  source/braille.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved, blocked/needs-testing

#13550 added support for delayed phonetic character descriptions
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/speech/speech.py
  source/synthDriverHandler.py
  tests/system/robot/symbolPronunciationTests.py
  tests/system/robot/symbolPronunciationTests.robot
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: blocked/needs-code-review, conceptApproved, audience/hearing-impaired

#13916 Start a style guide for the User Guide
  devDocs/featureFlags.md
  devDocs/userGuideStandards.md
  user_docs/styles.css
Labels: release/blocking

#13932 Fixup #13131, ensure speech doesn't interrupt when scrolling braille display
  source/braille.py
Labels: release/blocking

#13933 Review changelog and documentation changes for 2022.3
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: release/blocking

#13943 Remove `typing.Collection` from MRO of `FlagValueEnum`
  source/config/featureFlagEnums.py
Labels: release/blocking

#13954 Revert "Introducing table sayall commands (#13670)"
  source/documentBase.py
  source/speech/sayAll.py
  source/virtualBuffers/__init__.py
  source/virtualBuffers/gecko_ia2.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: release/blocking
