Repository nvaccess/nvda, pull requests merged in 2022-12, with the labels that each got.

#14324 Lower poll interval for blockUntilConditionMet
  source/utils/blockUntilConditionMet.py
  tests/system/libraries/SystemTestSpy/blockUntilConditionMet.py
  tests/unit/test_util/test_blockUntilConditionMet.py
Labels: blocked

#14425 Braille: report 'details' for non-landmarks
  source/braille.py
  tests/system/robot/chromeTests.py
  user_docs/en/changes.t2t
Labels: component/braille, component/braille-ux

#14261 Use highlighter during tests
  tests/system/nvdaSettingsFiles/standard-dontShowWelcomeDialog.ini
Labels: component/system-testing

#13798 Improve Paragraph Navigation - add single and multi line break style
  source/config/configSpec.py
  source/config/featureFlagEnums.py
  source/cursorManager.py
  source/documentNavigation/paragraphHelper.py
  source/documentNavigation/sentenceHelper.py
  source/editableText.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  tests/unit/test_paragraphHelper.py
  tests/unit/test_sentenceHelper.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: blocked/needs-code-review, merge-early

#14404 appModuleHandler.AppModule.appArchitecture: detect AMD64 apps in Windows 11 on ARM via kernel32.dll::GetProcessInformation
  source/appModuleHandler.py
  user_docs/en/changes.t2t
Labels: blocked/needs-testing
