Repository nvaccess/nvda, pull requests merged in 2022-03, with the labels that each got.

#13414 Ensure states/roles are unique
  source/controlTypes/role.py
  source/controlTypes/state.py
  user_docs/en/changes.t2t
Labels: audience/nvda-dev, blocked/api-breaking-change

#12951 update add-on api back compat for 2022.1
  source/addonAPIVersion.py
Labels: blocked/api-breaking-change, release/blocking

#13500 Add UI messages when an action cannot be performed
  source/globalCommands.py
  source/gui/__init__.py
  source/gui/blockAction.py
  source/gui/contextHelp.py
  source/gui/logViewer.py
  source/inputCore.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#13498 Move exit dialog to submodule
  source/globalCommands.py
  source/gui/__init__.py
  source/gui/exit.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#13345 Fix table navigation commands through merged cells by caching last column/row index
  source/documentBase.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  user_docs/en/changes.t2t
Labels: conceptApproved

#13470 Adding jump to first/last row/column commands in list views and Tree Views.
  source/NVDAObjects/behaviors.py
Labels: conceptApproved

#13501 Improve secure mode and secure screens documentation
  devDocs/technicalDesignOverview.md
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#13529 Release lock on mouse keys when exiting.
  source/globalCommands.py
  source/mouseHandler.py
  user_docs/en/changes.t2t
Labels: conceptApproved
