Repository nvaccess/nvda, pull requests merged in 2023-12, with the labels that each got.

#15823 UIA handler: work directly with UIA interfaces introduced in Windows 8 and later
  source/UIAHandler/__init__.py
Labels: conceptApproved

#15864 Add plural forms for needed strings in NVDA's code base
  source/NVDAObjects/IAccessible/sysTreeView32.py
  source/NVDAObjects/UIA/excel.py
  source/NVDAObjects/window/_msOfficeChart.py
  source/NVDAObjects/window/winword.py
  source/appModules/powerpnt.py
  source/appModules/soffice.py
  source/globalCommands.py
  source/gui/addonStoreGui/controls/details.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/inputGestures.py
  source/speech/speech.py
  source/touchHandler.py
  source/ui.py
  source/virtualBuffers/__init__.py
  tests/checkPot.py
  user_docs/en/changes.t2t
Labels: api-breaking-change

#15893 Make add-on store base end point part of the public API
  source/addonStore/network.py
Labels: blocked/needs-testing

#15830 Add a native selection mode to Gecko virtualBuffers
  nvdaHelper/ia2_sconscript
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  nvdaHelper/vbufBase/storage.cpp
  source/NVDAObjects/IAccessible/chromium.py
  source/NVDAObjects/window/winword.py
  source/XMLFormatting.py
  source/browseMode.py
  source/cursorManager.py
  source/virtualBuffers/__init__.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#15904 Remove a demo script
  source/NVDAObjects/IAccessible/winword.py
  user_docs/en/changes.t2t
Labels: api-breaking-change

#15967 Remove add-on modules imported in install tasks to avoid conflicts between add-ons
  requirements.txt
  source/addonHandler/__init__.py
  source/addonStore/install.py
  source/gui/addonGui.py
  source/systemUtils.py
Labels: blocked/needs-testing

#15960 Detach disabling "talk" speech mode warning dialog
  source/gui/settingsDialogs.py
Labels: blocked/needs-product-decision
