Repository nvaccess/nvda, pull requests merged in 2023-08, with the labels that each got.

#15269 Albatross: write timeout change and minor code refactoring
  source/brailleDisplayDrivers/albatross/constants.py
  source/brailleDisplayDrivers/albatross/driver.py
Labels: merge-early

#15205 Text alignment reporting and enhancements for MS Excel cells and MS Word text
  nvdaHelper/remote/WinWord/Constants.h
  nvdaHelper/remote/winword.cpp
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/UIA/__init__.py
  source/NVDAObjects/window/edit.py
  source/NVDAObjects/window/excel.py
  source/NVDAObjects/window/winword.py
  source/controlTypes/__init__.py
  source/controlTypes/formatFields.py
  source/speech/speech.py
  source/virtualBuffers/MSHTML.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15163 Update braille independently on caret
  source/NVDAObjects/UIA/winConsoleUIA.py
  source/NVDAObjects/behaviors.py
  source/braille.py
  source/globalCommands.py
  tests/unit/__init__.py
  user_docs/en/changes.t2t
Labels: conceptApproved, merge-early

#15335 Small BRLTTY driver improvements
  source/brailleDisplayDrivers/brltty.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved
