Repository nvaccess/nvda, pull requests merged in 2023-11, with the labels that each got.

#15783 WASAPI: Recover after the device is reconfigured or leaves exclusive mode.
  nvdaHelper/local/wasapi.cpp
  source/nvwave.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15797 Fix Command Quick Reference
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#15748 Edge with UIA: allow activating buttons in browse mode by walking ancestors until an action succeeds
  source/NVDAObjects/UIA/__init__.py
  source/UIAHandler/browseMode.py
  source/browseMode.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15799 Use UIA for syslistview32 controls backed by Windows Forms
  source/UIAHandler/__init__.py
  source/UIAHandler/utils.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15778 Suppress garbageHandler log warnings
  projectDocs/design/unreachableObjects.md
  source/config/configSpec.py
  source/garbageHandler.py
  source/gui/settingsDialogs.py
Labels: conceptApproved

#15772 bdDetect: swap KEY_* constants with enum
  source/bdDetect.py
  source/braille.py
  source/brailleDisplayDrivers/albatross/driver.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/baum.py
  source/brailleDisplayDrivers/brailleNote.py
  source/brailleDisplayDrivers/brailliantB.py
  source/brailleDisplayDrivers/eurobraille/driver.py
  source/brailleDisplayDrivers/freedomScientific.py
  source/brailleDisplayDrivers/handyTech.py
  source/brailleDisplayDrivers/hidBrailleStandard.py
  source/brailleDisplayDrivers/hims.py
  source/brailleDisplayDrivers/nattiqbraille.py
  source/brailleDisplayDrivers/seikantk.py
  source/brailleDisplayDrivers/superBrl.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15809 Fix reporting of native Word commands to jump to table boundaries
  source/NVDAObjects/IAccessible/winword.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15777 Mark add-on store code as public API
  source/addonHandler/__init__.py
  source/addonHandler/addonVersionCheck.py
  source/addonStore/__init__.py
  source/addonStore/dataManager.py
  source/addonStore/install.py
  source/addonStore/models/__init__.py
  source/addonStore/models/addon.py
  source/addonStore/models/channel.py
  source/addonStore/models/status.py
  source/addonStore/models/version.py
  source/addonStore/network.py
  source/core.py
  source/gui/__init__.py
  source/gui/addonGui.py
  source/gui/addonStoreGui/__init__.py
  source/gui/addonStoreGui/controls/__init__.py
  source/gui/addonStoreGui/controls/actions.py
  source/gui/addonStoreGui/controls/addonList.py
  source/gui/addonStoreGui/controls/details.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/addonStoreGui/viewModels/__init__.py
  source/gui/addonStoreGui/viewModels/action.py
  source/gui/addonStoreGui/viewModels/addonList.py
  source/gui/addonStoreGui/viewModels/store.py
  source/gui/installerGui.py
  source/updateCheck.py
  tests/unit/test_addonHandler/test_addonsState.py
Labels: conceptApproved

#15764 bdDetect: Enrich USB serial data with info about USB device
  source/bdDetect.py
  source/hwPortUtils.py
  user_docs/en/changes.t2t
Labels: api-breaking-change, conceptApproved

#15734 Update NVDA Controller client to support speaking SSML sequences
  extras/controllerClient/examples/example_c.c
  extras/controllerClient/examples/example_csharp/.gitignore
  extras/controllerClient/examples/example_csharp/NVAccess.NVDA.csproj
  extras/controllerClient/examples/example_csharp/NVDA.cs
  extras/controllerClient/examples/example_csharp/Program.cs
  extras/controllerClient/examples/example_csharp/SpeechPriority.cs
  extras/controllerClient/examples/example_csharp/SymbolLevel.cs
  extras/controllerClient/examples/example_python.py
  extras/controllerClient/readme.md
  extras/controllerClient/x86/example_c.c
  extras/controllerClient/x86/example_csharp.cs
  extras/controllerClient/x86/example_python.py
  nvdaHelper/client/client.cpp
  nvdaHelper/client/nvdaControllerClient.def
  nvdaHelper/interfaces/nvdaController/nvdaController.acf
  nvdaHelper/interfaces/nvdaController/nvdaController.idl
  nvdaHelper/local/nvdaController.cpp
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/local/rpcSrv.cpp
  nvdaHelper/local/sconscript
  nvdaHelper/remote/nvdaController.cpp
  nvdaHelper/remote/sconscript
  source/NVDAHelper.py
  source/characterProcessing.py
  source/config/configSpec.py
  source/speech/priorities.py
  source/speech/speech.py
  source/winAPI/constants.py
  user_docs/en/changes.t2t
Labels: Controller, conceptApproved

#15785 Report unavailable (disabled) objects during object navigation
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/__init__.py
  source/NVDAObjects/window/__init__.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#14888 Avoid UIA event flooding in NvDA by moving UIA event handler COM objects into c++
  nvdaHelper/local/UIAEventLimiter/api.cpp
  nvdaHelper/local/UIAEventLimiter/eventRecord.h
  nvdaHelper/local/UIAEventLimiter/rateLimitedEventHandler.cpp
  nvdaHelper/local/UIAEventLimiter/rateLimitedEventHandler.h
  nvdaHelper/local/UIAEventLimiter/utils.cpp
  nvdaHelper/local/UIAEventLimiter/utils.h
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/local/sconscript
  source/NVDAObjects/UIA/__init__.py
  source/UIAHandler/__init__.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved, merge-early

#15765 When re-installing incompatible add-ons preserve compatibility override
  source/addonHandler/__init__.py
  source/addonStore/install.py
  source/addonStore/models/status.py
  source/addonStore/models/version.py
  source/gui/addonGui.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15837 Windows 11 emoji panel: replace regular editable text with NVDAObjects.UIA.XamlEditableText
  source/appModules/windowsinternal_composableshell_experiences_textinput_inputapp.py
Labels: conceptApproved

#15826 Report keyboard shortcut when entering a list
  source/gui/installerGui.py
  source/speech/speech.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15825 Navigator object updates braille while navigating between FakeTableCell objects
  source/NVDAObjects/behaviors.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15838 Fix inaccurate text reporting in Visual Studio text controls
  source/NVDAObjects/UIA/__init__.py
Labels: conceptApproved

#15859 Add-on store: emit a namechange event when a list item is updated
  source/gui/addonStoreGui/controls/addonList.py
  user_docs/en/changes.t2t
Labels: feature/addon-store

#15771 Add a Rust example for the NVDA Controller Client
  extras/controllerClient/examples/example_rust/.gitignore
  extras/controllerClient/examples/example_rust/build.rs
  extras/controllerClient/examples/example_rust/cargo.toml
  extras/controllerClient/examples/example_rust/examples/example_rust.rs
  extras/controllerClient/examples/example_rust/readme.md
  extras/controllerClient/examples/example_rust/src/bindgen.rs
  extras/controllerClient/examples/example_rust/src/lib.rs
  extras/controllerClient/readme.md
  user_docs/en/changes.t2t
Labels: Controller, conceptApproved
