Repository nvaccess/nvda, pull requests merged in 2023-10, with the labels that each got.

#15556 When pickling addon state use only builtin types, and add unit test for the pickling and unpickling process.
  source/addonHandler/__init__.py
  tests/unit/test_addonHandler/__init__.py
  tests/unit/test_addonHandler/test_addonsState.py
Labels: conceptApproved

#15539 Fix link syntax in User Guide
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#15558 soffice: Announce actually deleted text on Ctrl+backspace
  source/appModules/soffice.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15560 Reduce verbosity when reporting Excel cell formatting
  source/NVDAObjects/window/excel.py
  source/speech/speech.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15544 Update to Python 3.11
  appveyor.yml
  appveyor/scripts/tests/unitTests.ps1
  appx/sconscript
  nvdaHelper/archBuild_sconscript
  nvdaHelper/local/nvdaHelperLocal.cpp
  nvdaHelper/readme.md
  projectDocs/dev/createDevEnvironment.md
  requirements.txt
  rununittests.bat
  sconstruct
  source/UIAHandler/types.py
  source/_addonStore/models/addon.py
  source/_addonStore/models/status.py
  source/_addonStore/models/version.py
  source/config/aggregatedSection.py
  source/config/featureFlagEnums.py
  source/globalVars.py
  source/installer.py
  source/louisHelper.py
  source/manifest.template.xml
  source/nvda_eoaProxy.pyw
  source/setup.py
  source/winVersion.py
  tests/system/robot/NVDAInstaller.robot
  tests/unit/test_baseObject.py
  tests/unit/test_braille/test_brailleDisplayDrivers.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
  venvUtils/ensureAndActivate.bat
  venvUtils/ensureVenv.py
Labels: api-breaking-change

#15638 Revert "NVDAObject.presentationType: groupings with position information but no name and no description should still be treated as content I.e. announced in focus ancestry. (#14878)"
  source/NVDAObjects/__init__.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15636 Update to flake8 4.0.1.
  requirements.txt
  user_docs/en/changes.t2t
Labels: conceptApproved

#15546 Python 3.11 upgrade cleanup
  source/_addonStore/dataManager.py
  source/_addonStore/install.py
  source/_addonStore/models/addon.py
  source/_addonStore/network.py
  source/addonHandler/__init__.py
  source/gui/_addonStoreGui/viewModels/addonList.py
  source/gui/_addonStoreGui/viewModels/store.py
  source/languageHandler.py
  source/monkeyPatches/__init__.py
  source/monkeyPatches/enumPatches.py
  source/utils/displayString.py
  source/visionEnhancementProviders/NVDAHighlighter.py
  source/winAPI/dpiAwareness.py
  source/winUser.py
  tests/unit/test_controlTypes.py
  user_docs/en/changes.t2t
Labels: api-breaking-change, conceptApproved

#15491 Update braille when control+v, control+x, control+y, control+z, backspace or control+backspace is pressed and UIA not used in ms word
  source/NVDAObjects/IAccessible/winword.py
  source/NVDAObjects/UIA/wordDocument.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15386 Expose number of rows/lines on multiline braille displays
  source/braille.py
  source/brailleDisplayDrivers/brltty.py
  tests/unit/test_braille/test_brailleDisplayDrivers.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15313 Update poedit appmodule for version 3.4+
  source/appModules/poedit.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: api-breaking-change, conceptApproved
