Repository nvaccess/nvda, pull requests merged in 2023-02, with the labels that each got.

#14570 Fix reporting time in foobar2000 over 24 hours
  source/NVDAObjects/__init__.py
  source/api.py
  source/appModules/foobar2000.py
  source/utils/localisation.py
  tests/unit/test_appModules/__init__.py
  tests/unit/test_appModules/test_foobar2000.py
  tests/unit/test_util/test_localisation.py
  user_docs/en/changes.t2t
Labels: api-breaking-change

#14172 Bump Add-on backwards compatibility
  source/addonAPIVersion.py
Labels: blocked

#14524 Refactor BrailleHandler.setDisplayByName
  source/braille.py
  user_docs/en/changes.t2t
Labels: merge-early

#13857 Change dash symbol pronunciation defaults
  source/locale/en/symbols.dic
  user_docs/en/changes.t2t
Labels: blocked/needs-product-decision

#14531 Add support for custom providers for braille display auto detection
  source/bdDetect.py
  source/braille.py
  source/core.py
  source/extensionPoints/__init__.py
  source/extensionPoints/util.py
  tests/unit/extensionPointTestHelpers.py
  tests/unit/test_bdDetect.py
  tests/unit/test_extensionPoints.py
  user_docs/en/changes.t2t
Labels: merge-early
