Repository nvaccess/nvda, pull requests merged in 2023-09, with the labels that each got.

#15200 Allow excluding display drivers from automatic detection
  source/bdDetect.py
  source/braille.py
  source/brailleDisplayDrivers/albatross/driver.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/baum.py
  source/brailleDisplayDrivers/brailleNote.py
  source/brailleDisplayDrivers/brailliantB.py
  source/brailleDisplayDrivers/eurobraille/driver.py
  source/brailleDisplayDrivers/freedomScientific.py
  source/brailleDisplayDrivers/handyTech.py
  source/brailleDisplayDrivers/hidBrailleStandard.py
  source/brailleDisplayDrivers/hims.py
  source/brailleDisplayDrivers/nattiqbraille.py
  source/brailleDisplayDrivers/seikantk.py
  source/brailleDisplayDrivers/superBrl.py
  source/config/configSpec.py
  source/config/profileUpgradeSteps.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved, merge-early

#15331 Continually refresh OCR and speak new text as it appears
  source/config/configSpec.py
  source/contentRecog/__init__.py
  source/contentRecog/recogUi.py
  source/contentRecog/uwpOcr.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/visionEnhancementProviders/screenCurtain.py
  tests/checkPot.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#15332 Implement tab navigation
  source/UIAHandler/browseMode.py
  source/browseMode.py
  source/virtualBuffers/MSHTML.py
  source/virtualBuffers/gecko_ia2.py
  user_docs/en/changes.t2t
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#15337 Create a friendlier system of project documentation
  .github/CONTRIBUTING.md
  nvdaHelper/readme.md
  projectDocs/community/readme.md
  projectDocs/dev/addons.md
  projectDocs/dev/buildingDevDocumentation.md
  projectDocs/dev/buildingNVDA.md
  projectDocs/dev/contributing.md
  projectDocs/dev/createDevEnvironment.md
  projectDocs/dev/readme.md
  projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
  projectDocs/issues/readme.md
  projectDocs/testing/automated.md
  projectDocs/testing/contributing.md
  projectDocs/testing/readme.md
  readme.md
  user_docs/en/userGuide.t2t
Labels: conceptApproved

#14488 Remove `SecureDesktopNVDAObject`, replace with extension point
  source/IAccessibleHandler/__init__.py
  source/core.py
  source/eventHandler.py
  source/utils/security.py
  source/winAPI/secureDesktop.py
  user_docs/en/changes.t2t
Labels: api-breaking-change

#15385 Remove scheduled deprecations for 2024.1
  source/bdDetect.py
  source/braille.py
  source/hwIo/base.py
  source/hwIo/ioThread.py
  user_docs/en/changes.t2t
Labels: api-breaking-change

#15271 Support Pitch, Rate and Volume commands properly in SAPI4
  source/synthDriverHandler.py
  source/synthDrivers/sapi4.py
  user_docs/en/changes.t2t
Labels: conceptApproved

#15433 Depend on supported command for capital pitch change
  source/speech/speech.py
  user_docs/en/changes.t2t
Labels: component/speech-synth-drivers, api-breaking-change
