Repository nvaccess/nvda, pull requests merged in 2024-09, with the labels that each got.

#16889 Use static ids in Poedit 3.5+
  source/appModules/poedit.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: app-specific, conceptApproved

#10990 Word 365: do not announce font attribute toggle messages if raised from UIA notification event
  source/NVDAObjects/UIA/wordDocument.py
Labels: bug, app/microsoft-office, bug/double-speaking, conceptApproved, merge-early, blocked/needs-testing

#17050 add ability to translate the user guide on Crowdin
  .github/workflows/regenerate_english_userDocs_translation_source.yml
  sconstruct
  tests/markdownTranslate/en_2024.2_userGuide.md
  tests/markdownTranslate/en_2024.3beta6_userGuide.md
  tests/markdownTranslate/fr_pretranslated_2024.2_userGuide.md
  tests/markdownTranslate/fr_pretranslated_2024.3beta6_userGuide.md
  tests/unit/test_markdownTranslate.py
  user_docs/en/userGuide.xliff
  user_docs/markdownTranslate.py
Labels: conceptApproved

#17100 User docs github action: push via ssh / deploy key
  .github/workflows/regenerate_english_userDocs_translation_source.yml
Labels: conceptApproved

#16591 Keystrokes to adjust applications volume and mute [take 2]
  source/audio/__init__.py
  source/audio/appsVolume.py
  source/audio/soundSplit.py
  source/audio/utils.py
  source/config/configSpec.py
  source/config/featureFlagEnums.py
  source/core.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#16820 Remove old winTerminalUIA module attribute
  source/NVDAObjects/UIA/winConsoleUIA.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#16768 Remove FakeEmbeddingTextInfo which is no longer necessary.
  source/NVDAObjects/IAccessible/ia2TextMozilla.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved, merge-early

#17099 Add ability to specify add-on store metadata URL from within NVDA
  requirements.txt
  source/addonStore/dataManager.py
  source/addonStore/network.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16671 Add-on Store: Added the action to cancel the install of a add-on when it is being downloaded.
  source/addonStore/models/addon.py
  source/addonStore/network.py
  source/gui/addonStoreGui/controls/actions.py
  source/gui/addonStoreGui/viewModels/addonList.py
  source/gui/addonStoreGui/viewModels/store.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#16994 Add ability to recognize links to the same page
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/UIA/chromium.py
  source/NVDAObjects/__init__.py
  source/braille.py
  source/browseMode.py
  source/config/configSpec.py
  source/controlTypes/processAndLabelStates.py
  source/controlTypes/state.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/utils/urlUtils.py
  source/virtualBuffers/gecko_ia2.py
  tests/system/nvdaSettingsFiles/standard-dontShowWelcomeDialog.ini
  tests/unit/test_util/test_urlUtils.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: merge-early, blocked/needs-product-decision

#17017 Enable unicode normalization by default for speech
  source/config/configSpec.py
  tests/system/nvdaSettingsFiles/standard-doShowWelcomeDialog.ini
  tests/system/nvdaSettingsFiles/standard-dontShowExitDialog.ini
  tests/system/nvdaSettingsFiles/standard-dontShowWelcomeDialog.ini
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#17145 Fix not being able to rebuild after SCons cleanup
  source/comInterfaces/readme.md
  source/comInterfaces_sconscript
Labels: conceptApproved

#17142 Fix braille settings controls layout
  source/gui/settingsDialogs.py
Labels: conceptApproved

#17143 sconstruct: correctly detect the language of xliff files when trying to skip English
  sconstruct
Labels: conceptApproved

#17147 soffice: Report keyboard-triggered font size change
  source/appModules/soffice.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#17130 Fix popup menu item reading on Thunderbird
  source/appModules/thunderbird.py
  user_docs/en/changes.md
Labels: conceptApproved

#17158 Fix config profiles quickly get polluted with untouched settings
  source/config/__init__.py
  tests/unit/test_config.py
  user_docs/en/changes.md
Labels: conceptApproved

#17153 soffice: Report keyboard-triggered paragraph style change
  source/appModules/soffice.py
  user_docs/en/changes.md
Labels: conceptApproved

#17135 Add ability to sort add-ons by columns
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/addonStoreGui/viewModels/addonList.py
  tests/manual/addonStore.md
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17184 Fix audio panel layout
  source/gui/settingsDialogs.py
Labels: conceptApproved

#17191 Remove unused 'upgrade' config profile section
  source/config/__init__.py
  source/config/configSpec.py
  user_docs/en/changes.md
Labels: api-breaking-change

#17047 Correct internal gesture ID for Seika Notetaker
  source/brailleDisplayDrivers/seikantk.py
  user_docs/en/changes.md
Labels: component/braille-display-drivers, api-breaking-change, blocked/needs-info, conceptApproved

#17181 Update wxPython to 4.2.2, using 32-bit wheel hosted on PyPI
  requirements.txt
  user_docs/en/changes.md
Labels: conceptApproved

#12355 Refactor COM Registration Fixing Tool part 2: remove bugs, return Windows errors, improve UX
  source/gui/__init__.py
  source/gui/logViewer.py
  source/gui/nvdaControls.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#16830 Update and simplify COPYING.txt
  copying.txt
  projectDocs/dev/contributing.md
  projectDocs/dev/copyrightHeaders.md
  pyproject.toml
Labels: conceptApproved

#17117 Creation of NVDA development roadmap
  readme.md
Labels: conceptApproved

#17151 Add the ability to specify NVDA update check URL from within NVDA
  source/config/configSpec.py
  source/gui/_SetURLDialog.py
  source/gui/settingsDialogs.py
  source/updateCheck.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17197 Speech feedback on more Word formatting shortcuts
  source/NVDAObjects/window/winword.py
  source/appModules/winword.py
  user_docs/en/changes.md
Labels: conceptApproved

#17203 Document silent uninstallation of NVDA in the user guide
  user_docs/en/userGuide.md
Labels: conceptApproved
