Repository nvaccess/nvda, pull requests merged in 2024-06, with the labels that each got.

#16627 Update and migrate translating dic/ini files from wiki
  projectDocs/dev/contributing.md
  projectDocs/dev/developerGuide/developerGuide.md
  projectDocs/translating/readme.md
Labels: conceptApproved

#16665 Add `.coderabbit.yml` config and update pull request template
  .coderabbit.yml
  .github/PULL_REQUEST_TEMPLATE.md
  projectDocs/dev/contributing.md
  projectDocs/dev/githubPullRequestTemplateExplanationAndExamples.md
Labels: conceptApproved

#16622 Unicode normalization follow up, adding character navigation and several fixes
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/local/nvdaHelperLocal.h
  nvdaHelper/local/textUtils.cpp
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/nvdaControls.py
  source/gui/settingsDialogs.py
  source/speech/commands.py
  source/speech/manager.py
  source/speech/speech.py
  source/textUtils/__init__.py
  source/textUtils/uniscribe.py
  tests/unit/__init__.py
  tests/unit/test_speech.py
  tests/unit/test_textUtils.py
  user_docs/en/userGuide.md
Labels: conceptApproved

#16636 Notifying users of available add-on updates
  requirements.txt
  source/addonStore/dataManager.py
  source/config/__init__.py
  source/config/configFlags.py
  source/config/configSpec.py
  source/core.py
  source/gui/__init__.py
  source/gui/addonStoreGui/__init__.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/addonStoreGui/viewModels/store.py
  source/gui/settingsDialogs.py
  source/utils/schedule.py
  tests/manual/addonStore.md
  tests/manual/createUpdatableAddons.ps1
  tests/unit/test_util/test_schedule.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16424 Reenable chrome tests
  tests/system/libraries/_chromeArgs.py
  tests/system/robot/chromeTests.robot
Labels: conceptApproved

#16670 QuickNav next menu command: adding more IA2 roles
  source/virtualBuffers/gecko_ia2.py
Labels: conceptApproved

#16668 Add support for Activator Pro models to Help Tech Braille driver.
  source/brailleDisplayDrivers/handyTech.py
  user_docs/en/changes.md
Labels: conceptApproved

#16359 Make the incompatibility message more explicit
  source/addonStore/models/version.py
Labels: conceptApproved

#16696 Make CLI help dialog visually readable
  source/nvda.pyw
Labels: sightedDevIdeal

#16711 When handling caret movement, fetch the new caret info after checking for a pending caret event.
  source/editableText.py
  user_docs/en/changes.md
Labels: merge-early

#16672 Windows 10/11 Calculator: report correct number after paste by fetching the value directly from the UI element.
  source/appModules/calculator.py
  user_docs/en/changes.md
Labels: conceptApproved

#16340 Add com port option in Braille Display Select Dialog and fix Serial Connection error
  source/bdDetect.py
  source/brailleDisplayDrivers/hims.py
Labels: conceptApproved, merge-early

#16248 Support for text review commands on object name in Visual Studio Code
  source/appModules/code.py
  user_docs/en/changes.md
Labels: conceptApproved

#16673 Replace scons app signing from signtool to signpath
  .gitignore
  appveyor.yml
  appveyor/scripts/decryptFilesForSigning.ps1
  appveyor/scripts/setSconsArgs.ps1
  appveyor/scripts/sign.ps1
  appx/sconscript
  nvdaHelper/archBuild_sconscript
  nvdaHelper/liblouis/sconscript
  projectDocs/dev/buildingNVDAOnAppVeyor.md
  sconstruct
Labels: conceptApproved, merge-early

#12816 Update .gitattributes to prefer LF
  .git-blame-ignore-revs
  .gitattributes
  projectDocs/dev/codingStandards.md
Labels: release/blocking, merge-early
