Repository nvaccess/nvda, pull requests merged in 2024-05, with the labels that each got.

#16446 Create PR revert template
  .github/PULL_REQUEST_TEMPLATE/revert.md
  projectDocs/community/releaseProcess.md
Labels: conceptApproved, queued for merge

#16463 Remove redundant braille.BrailleHandler.update executions
  source/braille.py
Labels: conceptApproved, merge-early, queued for merge

#16472 Add pfx files to .gitignore
  .gitignore
Labels: conceptApproved, queued for merge

#16480 Properly support MSVC 14.40 toolset for getting the universal CRT files
  nvdaHelper/localWin10/sconscript
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16208 Support for custom braille tables
  .gitignore
  contributors.txt
  nvdaHelper/liblouis/sconscript
  projectDocs/dev/developerGuide/developerGuide.md
  source/addonHandler/__init__.py
  source/braille.py
  source/brailleInput.py
  source/brailleTables.py
  source/config/__init__.py
  source/core.py
  source/gui/settingsDialogs.py
  source/louisHelper.py
  tests/unit/test_louisHelper.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early, queued for merge

#16321 Use fixed width font in the log viewer and the Python console
  source/gui/logViewer.py
  source/pythonConsole.py
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16445 Only report captions when entering and exiting them
  source/textInfos/__init__.py
  user_docs/en/changes.md
Labels: blocked/merge-conflicts, conceptApproved, queued for merge

#16471 Report aria-label and aria-description even when parent has no visible children
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  user_docs/en/changes.md
Labels: blocked/merge-conflicts, conceptApproved, queued for merge

#16411 Support aria-errormessage
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp
  nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.h
  source/IAccessibleHandler/types.py
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/__init__.py
  source/braille.py
  source/speech/speech.py
  tests/system/robot/chromeTests.py
  tests/system/robot/chromeTests.robot
  user_docs/en/changes.md
Labels: blocked/merge-conflicts, conceptApproved, queued for merge

#16413 soffice: Report keyboard-triggered formatting toggles in Writer
  source/appModules/soffice.py
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16473 Correctly announce selection changes in inline cel edit control in Microsoft Excel
  source/eventHandler.py
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16497 Fix routing to account for rawToContentPos
  source/braille.py
Labels: queued for merge

#16483 Refactor DiffMatchPatch diff handler
  source/diffHandler.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early

#16423 fix up documentation changes for 2024.2
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, queued for merge

#16425 Fix numbered headings for Arabic
  user_docs/numberedHeadings.css
Labels: conceptApproved, queued for merge

#16430 Fix exception when triggering style navigation commands in an empty document
  source/browseMode.py
Labels: conceptApproved, queued for merge

#16450 Fix hanging during text paragraph navigation in UIA edge
  source/browseMode.py
Labels: conceptApproved, queued for merge

#16455 Fix Edit.makeTextInfo(caret) when selection is present
  source/NVDAObjects/window/edit.py
Labels: conceptApproved, queued for merge

#16461 Recover safely if the add-on store cache is invalid
  source/addonStore/dataManager.py
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16447 Fix exception during textInfos.moveToCodepointOffset when some characters correspond to 0 pythonic characters
  source/textInfos/__init__.py
  tests/unit/test_textInfos.py
Labels: conceptApproved

#16470 Add Lao Grade 1 braille table
  source/brailleTables.py
  user_docs/en/changes.md
Labels: conceptApproved, queued for merge

#16440 Revert "Keystrokes to adjust applications volume and mute"
  source/audio/__init__.py
  source/audio/soundSplit.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, queued for merge

#16540 Rewording and fixes in documentation
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16539 Revert "Use moveToCodepointOffset for cursor routing"
  source/braille.py
  tests/unit/__init__.py
  tests/unit/test_braille/test_routing.py
  tests/unit/textProvider.py
  user_docs/en/changes.md
Labels: conceptApproved

#16541 Windows 11 IME: announce visible candidates when the IME interface opens
  source/appModules/windowsinternal_composableshell_experiences_textinput_inputapp.py
  user_docs/en/changes.md
Labels: conceptApproved

#16452 Create special_case_issue.md issue template
  .github/ISSUE_TEMPLATE/special_case_issue.md
  projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
Labels: conceptApproved

#16577 Update and migrate translating page from wiki
  .github/CONTRIBUTING.md
  projectDocs/community/readme.md
  projectDocs/dev/developerGuide/developerGuide.md
  projectDocs/translating/readme.md
Labels: conceptApproved

#16550 reduce braille.BrailleHandler.update redundant executions
  source/braille.py
Labels: conceptApproved, blocked/needs-testing

#16521 Add Unicode Normalization to speech and braille
  source/braille.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/speech/speech.py
  source/textUtils.py
  tests/unit/test_textUtils.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16551 Re-order focus events for menuitemcheckbox and menuitemradio
  source/eventHandler.py
  user_docs/en/changes.md
Labels: conceptApproved

#16553 Add section on add-on store to the Quick Start Guide in the User Guide
  user_docs/en/userGuide.md
Labels: conceptApproved

#16618 Updates to Add-ons section of Quick start guide
  user_docs/en/userGuide.md
Labels: conceptApproved

#16481 Recognize Windows 11 build 26100 as 24H2 RTM
  appx/manifest.xml.subst
  source/winVersion.py
Labels: blocked, conceptApproved, queued for merge
