Repository nvaccess/nvda, pull requests merged in 2024-10, with the labels that each got.

#17219 Honour multi keypress timeout for NVDA key
  source/keyboardHandler.py
Labels: conceptApproved

#17214 Improve translation system workflow
  .gitignore
  .pre-commit-config.yaml
  appveyor/scripts/setSconsArgs.ps1
  projectDocs/dev/developerGuide/sconscript
  projectDocs/translating/crowdin.md
  projectDocs/translating/readme.md
  pyproject.toml
  requirements.txt
  sconstruct
  user_docs/markdownTranslate.py
  user_docs/md2html.py
  user_docs/nvdaL10nUtil.py
Labels: conceptApproved

#17228 Update Add-on Store mirror to use new UX
  source/gui/_SetURLDialog.py
  source/gui/settingsDialogs.py
  user_docs/en/userGuide.md
Labels: conceptApproved

#17278 Update SCons
  nvdaHelper/liblouis/sconscript
  nvdaHelper/localWin10/sconscript
  requirements.txt
  user_docs/en/changes.md
Labels: component/build, audience/nvda-dev

#17222 Set default input and translation tables according to NVDA's language
  source/braille.py
  source/brailleInput.py
  source/brailleTables.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
Labels: conceptApproved

#17276 Add ability to read math in PDF documents
  nvdaHelper/vbufBackends/adobeAcrobat/adobeAcrobat.cpp
  source/NVDAObjects/IAccessible/adobeAcrobat.py
  user_docs/en/changes.md
Labels: conceptApproved

#17200 Remove "or later" from copying.txt
  copying.txt
  pyproject.toml
Labels: release/blocking

#17333 Update robot framework to 7.1.1
  requirements.txt
  user_docs/en/changes.md
Labels: conceptApproved

#17324 Add ability to report the document layout in Microsoft Word
  source/appModules/winword.py
  user_docs/en/changes.md
Labels: conceptApproved
