Repository nvaccess/nvda, pull requests merged in 2024-08, with the labels that each got.

#16868 Fixup precommit and update Ruff
  .coderabbit.yml
  .pre-commit-config.yaml
  requirements.txt
  sconstruct
  user_docs/en/changes.md
  venvUtils/ensureVenv.py
Labels: conceptApproved

#16866 Configure pre-commit CI
  .pre-commit-config.yaml
  projectDocs/dev/contributing.md
  projectDocs/testing/automated.md
  readme.md
  source/speech/commands.py
Labels: conceptApproved

#16906 Add ability to report start of paragraphs in braille
  source/braille.py
  source/config/configFlags.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16808 Modernize the example code blocks in the developer's guide
  projectDocs/dev/developerGuide/developerGuide.md
Labels: conceptApproved

#16779 add github action to assign milestone automatically
  .github/workflows/assign-milestone-on-close.yml
Labels: conceptApproved

#16953 Add function type information to functions in NVDAObjects/JAB/init.py
  source/NVDAObjects/JAB/__init__.py
Labels: conceptApproved

#16947 Add ability to speak character when cursor routing
  source/braille.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#16369 Give ui.browseableMessage the ability to show copy and close buttons after the message, and add buttons to some instances
  source/globalCommands.py
  source/message.html
  source/ui.py
  user_docs/en/changes.md
Labels: conceptApproved

#16971 Add Documentation for how to Remotely Debug NVDA
  projectDocs/dev/readme.md
  projectDocs/dev/remoteDebugging.md
Labels: conceptApproved

#17028 Support compiling with VS 2022 V17.11
  nvdaHelper/local/beeps.cpp
Labels: merge-early

#17030 Review 2024.4 changelog and documentation changes
  projectDocs/dev/developerGuide/developerGuide.md
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17033 Start dev cycle for 2025.1
  source/addonAPIVersion.py
  source/buildVersion.py
  source/versionInfo.py
  user_docs/en/changes.md
Labels: conceptApproved

#17040 Update auto milestone action to only apply to completed issues and merged PRs
  .github/workflows/assign-milestone-on-close.yml
Labels: conceptApproved

#17029 Reformat build guide and add note about building serially when debugging the build process
  projectDocs/dev/buildingNVDA.md
Labels: audience/nvda-dev, conceptApproved

#17035 Remove unit tests for linking code between `reportFontAttributes` and `fontAttributeReporting`
  tests/unit/test_config.py
Labels: conceptApproved

#17049 CursorManager._caretMovementScriptHelper: return early if another script is waiting.
  source/cursorManager.py
  user_docs/en/changes.md
Labels: conceptApproved

#17051 VS Code is no longer as sluggish when arrowing up and down through large files
  source/appModules/code.py
  user_docs/en/changes.md
Labels: conceptApproved

#17042 Work around broken Data validation dropdown lists in Microsoft Excel
  source/appModules/excel.py
  user_docs/en/changes.md
Labels: conceptApproved

#17048 Revert "Use UIA caret events in Windows Terminal (#16873)"
  source/NVDAObjects/UIA/winConsoleUIA.py
Labels: conceptApproved

#17007 Native support for the Dot Pad tactile graphic Braille Display from Dot Inc
  source/brailleDisplayDrivers/dotPad/__init__.py
  source/brailleDisplayDrivers/dotPad/defs.py
  source/brailleDisplayDrivers/dotPad/driver.py
  source/setup.py
  source/tactile/__init__.py
  source/tactile/braille.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#17043 Enable debug logging when restarting NVDA with add-ons
  source/gui/exit.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17018 Give ui.browseableMessage the ability to show copy and close buttons after the message, and add buttons to some instances (2nd try)
  source/globalCommands.py
  source/message.html
  source/ui.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early

#17015 Fix PowerPoint caret reporting when text contains wide characters, and overall improvement of TextInfo implementation
  source/appModules/powerpnt.py
  source/textInfos/offsets.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early

#17061 Update comtypes to version 1.4.6
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
  source/comInterfaces/UIAutomationClient.py
  source/comInterfaces/_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py
  source/comInterfaces/readme.md
  source/comInterfaces_sconscript
  source/monkeyPatches/comtypesMonkeyPatches.py
  user_docs/en/changes.md
Labels: merge-early

#17011 Text displayed on a multiline braille display will now word wrap on every row in the braille window, not just at the end
  projectDocs/dev/developerGuide/developerGuide.md
  source/braille.py
  tests/unit/test_braille/test_handlerExtensionPoints.py
  tests/unit/test_braille/test_normalizeCellArraySize.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early
