Repository nvaccess/nvda, pull requests merged in 2025-09, with the labels that each got.

#18806 Remove junk files
  .gitignore
  source/locale/log.txt
  tests/system/settingsCache/2020.4/Advanced.txt
  tests/system/settingsCache/2020.4/Braille.txt
  tests/system/settingsCache/2020.4/Browse Mode.txt
  tests/system/settingsCache/2020.4/Document Formatting.txt
  tests/system/settingsCache/2020.4/General.txt
  tests/system/settingsCache/2020.4/Input Composition.txt
  tests/system/settingsCache/2020.4/Keyboard.txt
  tests/system/settingsCache/2020.4/Mouse.txt
  tests/system/settingsCache/2020.4/Object Presentation.txt
  tests/system/settingsCache/2020.4/Review Cursor.txt
  tests/system/settingsCache/2020.4/Speech.txt
  tests/system/settingsCache/2020.4/Vision.txt
Labels: conceptApproved

#18834 Move more raw ctypes calls to winBindings
  source/IAccessibleHandler/__init__.py
  source/NVDAHelper/__init__.py
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/window/edit.py
  source/UIAHandler/__init__.py
  source/_remoteClient/localMachine.py
  source/appModuleHandler.py
  source/audioDucking.py
  source/objbase.py
  source/objidl.py
  source/oleacc.py
  source/shlobj.py
  source/synthDrivers/sapi4.py
  source/synthDrivers/sapi5.py
  source/systemUtils.py
  source/touchHandler.py
  source/watchdog.py
  source/winAPI/dpiAwareness.py
  source/winBindings/advapi32.py
  source/winBindings/dbgHelp.py
  source/winBindings/kernel32.py
  source/winBindings/ole32.py
  source/winBindings/oleacc.py
  source/winBindings/oleaut32.py
  source/winBindings/rpcrt4.py
  source/winBindings/sas.py
  source/winBindings/shcore.py
  source/winBindings/uiAutomationCore.py
  source/winKernel.py
  source/windowUtils.py
Labels: conceptApproved

#18833 Fix app module loading when no process handle can be fetched
  source/appModuleHandler.py
  source/oleacc.py
  source/winBindings/user32.py
  source/winKernel.py
  source/winUser.py
  user_docs/en/changes.md
Labels: conceptApproved

#18839 NVDAObjects.IAccessible.sysListView32: ctypes.c_void_p -> ctypes.c_ulong for 32-bit LVItem and LVColumn structures
  source/NVDAObjects/IAccessible/sysListView32.py
Labels: conceptApproved

#18847 Fix errors sorting add-ons
  source/gui/addonStoreGui/controls/details.py
  source/gui/addonStoreGui/viewModels/addonList.py
Labels: conceptApproved

#18858 Fix UWP OCR on 64 bit NVDA
  source/NVDAHelper/__init__.py
  source/NVDAHelper/localWin10.py
  source/contentRecog/uwpOcr.py
  source/screenBitmap.py
  user_docs/en/changes.md
Labels: api-breaking-change

#18895 Fix PR status checks
  .github/workflows/testAndPublish.yml
Labels: ci-cd

#15320 Use GitHub forms for issues
  .github/ISSUE_TEMPLATE/01-bug_report.yaml
  .github/ISSUE_TEMPLATE/02-feature_request.yaml
  .github/ISSUE_TEMPLATE/03-special_case_issue.yaml
  .github/ISSUE_TEMPLATE/04-developer_facing_changes.yaml
  .github/ISSUE_TEMPLATE/11-bug_report.md
  .github/ISSUE_TEMPLATE/12-feature_request.md
  .github/ISSUE_TEMPLATE/13-special_case_issue.md
  .github/ISSUE_TEMPLATE/14-developer_facing_changes.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/developer_facing_changes.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/special_case_issue.md
  projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
Labels: conceptApproved

#18942 Fix WindowFromAccessibleObject
  source/IAccessibleHandler/__init__.py
  source/oleacc.py
Labels: conceptApproved

#18851 Modernize installer and reg key usage
  source/NVDAState.py
  source/addonHandler/__init__.py
  source/config/registry.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/installerGui.py
  source/installer.py
  source/winBindings/advapi32.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#18960 Fix report time
  source/winKernel.py
Labels: conceptApproved

#18816 Added ability to see changelog from the add-on store and Updatable add-ons dialog
  projectDocs/dev/developerGuide/developerGuide.md
  source/addonStore/models/addon.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/viewModels/store.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved
