Repository nvaccess/nvda, pull requests merged in 2025-06, with the labels that each got.

#17782 Minor improvements to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
  projectDocs/dev/githubPullRequestTemplateExplanationAndExamples.md
Labels: conceptApproved

#18139 Create testing plan for updating to 64bit
  tests/manual/updatingTo64bit.md
Labels: conceptApproved, epic/64bit-migration

#18198 Update uv to fix `runnvda.bat`
  .github/workflows/testAndPublish.yml
  .pre-commit-config.yaml
  appveyor/scripts/pushPackagingInfo.ps1
  appveyor/scripts/tests/licenseCheck.ps1
  ensureuv.bat
  ensureuv.ps1
  pyproject.toml
  runnvda.bat
  scons.bat
  uv.lock
Labels: conceptApproved

#18069 Update SCons 4.8.1 to 4.9.1
  pyproject.toml
  user_docs/en/changes.md
  uv.lock
Labels: conceptApproved, merge-early

#18228 Improve reliability in the Start Menu in Windows 11 24h2.
  source/appModules/searchui.py
  user_docs/en/changes.md
Labels: conceptApproved

#18216 Windows 11 Notepad: reclassify "go to line" edit field as a proper edit field
  source/appModules/notepad.py
  user_docs/en/changes.md
Labels: conceptApproved

#18319 UIA notification event handler: NotificationKind -> notificationKind, NotificationProcessing -> notificationProcessing (argument name consistency)
  source/UIAHandler/__init__.py
  source/appModuleHandler.py
  source/appModules/explorer.py
Labels: conceptApproved

#18318 Revert #17573 and #16248
  source/appModules/code.py
Labels: conceptApproved

#18243 fix up features for github actions
  .github/workflows/testAndPublish.yml
  ci/scripts/tests/systemTests.ps1
Labels: conceptApproved

#18330 Add documentation for CI/CD set up
  .github/workflows/testAndPublish.yml
  ci/README.md
  ci/scripts/setSconsArgs.ps1
Labels: release/blocking-beta

#18293 Review 2025.2 changelog documentation changes
  user_docs/en/changes.md
Labels: conceptApproved, release/blocking-beta
