Repository nvaccess/nvda, pull requests merged in 2025-08, with the labels that each got.

#18444 Automatically detect Dot Pad displays over USB
  source/brailleDisplayDrivers/dotPad/driver.py
  source/config/configSpec.py
  source/config/profileUpgradeSteps.py
  tests/unit/test_config.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#18608 Encapsulate registry keys more consistently
  sconstruct
  site_scons/site_tools/doxygen.py
  source/NVDAState.py
  source/_remoteClient/localMachine.py
  source/_remoteClient/urlHandler.py
  source/config/__init__.py
  source/config/registry.py
  source/easeOfAccess.py
  source/installer.py
  source/mathType.py
  source/systemUtils.py
  source/winVersion.py
  user_docs/en/changes.md
Labels: conceptApproved

#18601 Persist remote connect dialog options
  source/NVDAState.py
  source/_remoteClient/dialogs.py
  source/gui/__init__.py
  user_docs/en/changes.md
Labels: conceptApproved

#18701 Persist selected index in Remote Access connection dialog"
  source/_remoteClient/dialogs.py
  source/gui/persistenceHandler.py
  user_docs/en/changes.md
Labels: conceptApproved

#18682 remove glob import from versionInfo
  appx/sconscript
  projectDocs/dev/developerGuide/conf.py
  projectDocs/dev/developerGuide/developerGuide.md
  sconstruct
  source/appModules/nvda.py
  source/buildVersion.py
  source/core.py
  source/gui/__init__.py
  source/gui/startupDialogs.py
  source/installer.py
  source/setup.py
  source/updateCheck.py
  source/versionInfo.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#18348 Fix OffsetTextInfo.collapse() and OffsetTextInfo.move()
  source/NVDAObjects/window/scintilla.py
  source/textInfos/offsets.py
  tests/system/robot/chromeTests.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved, merge-early

#18717 simplify encoding standards
  projectDocs/dev/codingStandards.md
Labels: conceptApproved

#18726 Split Turkish braille tables
  source/brailleTables/__tables.py
Labels: conceptApproved

#18672 Add-on manifest: add 'changelog' key to document changes for the latest add-on release
  projectDocs/dev/developerGuide/developerGuide.md
  source/addonHandler/__init__.py
  user_docs/en/changes.md
Labels: conceptApproved

#18744 Fix issues in uniscribe code
  nvdaHelper/local/textUtils.cpp
  source/textInfos/offsets.py
  source/textUtils/uniscribe.py
  user_docs/en/changes.md
Labels: conceptApproved, merge-early

#18724 Detect and report the status bar in Visual Studio Code
  .github/workflows/testAndPublish.yml
  source/appModules/code.py
  tests/system/libraries/SystemTestSpy/windows.py
  tests/system/libraries/VSCodeLib.py
  tests/system/robot/vscodeTests.py
  tests/system/robot/vscodeTests.robot
  user_docs/en/changes.md
Labels: conceptApproved

#18571 Move Windows API bindings out of hwPortUtils
  source/hwPortUtils.py
  source/utils/_deprecate.py
  source/winAPI/constants.py
  source/winBindings/advapi32.py
  source/winBindings/bthprops.py
  source/winBindings/cfgmgr32.py
  source/winBindings/hid.py
  source/winBindings/setupapi.py
  user_docs/en/changes.md
Labels: conceptApproved

#18688 Enforce Windows 10 requirement for NVDA
  nvdaHelper/archBuild_sconscript
  nvdaHelper/readme.md
  projectDocs/dev/createDevEnvironment.md
  projectDocs/dev/developerGuide/developerGuide.md
  source/NVDAObjects/UIA/__init__.py
  source/UIAHandler/__init__.py
  source/appModules/excel.py
  source/appModules/outlook.py
  source/manifest.template.xml
  source/synthDriverHandler.py
  source/synthDrivers/oneCore.py
  source/winAPI/sessionTracking.py
  source/winVersion.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: api-breaking-change

#18809 document deprecation utils
  projectDocs/dev/deprecations.md
Labels: conceptApproved
