Repository nvaccess/nvda, pull requests merged in 2025-04, with the labels that each got.

#17817 Fix SAPI4 WASAPI implementation
  source/monkeyPatches/comtypesMonkeyPatches.py
  source/synthDrivers/sapi4.py
Labels: conceptApproved

#17835 Translate French gestures for 2025.1
  source/locale/fr/gestures.ini
Labels: conceptApproved

#17728 Use GitHub Actions to build and test NVDA
  .github/workflows/testAndPublish.yml
  .pre-commit-config.yaml
  ci/README.md
  ci/scripts/installNVDA.ps1
  ci/scripts/setBuildVersionVars.ps1
  ci/scripts/setSconsArgs.ps1
  ci/scripts/tests/beforeTests.ps1
  ci/scripts/tests/licenseCheck.ps1
  ci/scripts/tests/systemTests.ps1
  ci/scripts/tests/translationCheck.ps1
  ci/scripts/tests/unitTests.ps1
  pyproject.toml
  tests/checkPot.py
  tests/unit/test_checkPot/__init__.py
Labels: conceptApproved

#17895 Review 2025.1 changelog documentation changes
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: release/blocking, release/blocking-beta

#17907 Disable GH Actions releases
  .github/workflows/testAndPublish.yml
Labels: release/blocking-beta

#17909 Regenerate english user docs workflow: correct path to markdownTranslate.py
  .github/workflows/regenerate_english_userDocs_translation_source.yml
Labels: conceptApproved

#17913 Follow-up #17905: Speak typed characters in classic Calculator when echo mode is 'Only in edit controls'.
  source/appModules/calc.py
Labels: conceptApproved

#17911 Simplify getDocFilePath function
  source/documentationUtils.py
  source/installer.py
  user_docs/en/changes.md
Labels: conceptApproved

#17865 Rationalise Remote gestures
  source/globalCommands.py
  user_docs/en/userGuide.md
Labels: conceptApproved, release/blocking-beta

#17814 Update Remote's dialogs to better match NVDA
  source/config/configFlags.py
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/remoteClient/client.py
  source/remoteClient/dialogs.py
  source/remoteClient/menu.py
  user_docs/en/userGuide.md
Labels: conceptApproved, release/blocking-beta

#17883 Fix issues with pushing the clipboard
  source/remoteClient/client.py
  source/remoteClient/session.py
  tests/unit/test_remote/test_remote_client.py
Labels: conceptApproved

#17972 Clear leftover audio data in SAPI5 SonicStream
  source/synthDrivers/sapi5.py
Labels: conceptApproved, blocked/needs-testing

#17968 Disallow initiating a new Remote Access session when in Secure Mode
  source/_remoteClient/client.py
  source/_remoteClient/menu.py
  source/globalCommands.py
  user_docs/en/userGuide.md
Labels: conceptApproved

#17943 Fix up user-facing Remote Access terminology
  source/_remoteClient/client.py
  source/_remoteClient/cues.py
  source/_remoteClient/dialogs.py
  source/_remoteClient/localMachine.py
  source/_remoteClient/menu.py
  source/_remoteClient/session.py
  source/config/configFlags.py
  source/core.py
  source/globalCommands.py
  source/gui/blockAction.py
  source/gui/settingsDialogs.py
  tests/unit/test_remote/test_remoteClient.py
  user_docs/en/userGuide.md
Labels: conceptApproved

#17970 Allow Remote Access leaders to regain control after the last follower has disconnected
  source/_remoteClient/client.py
Labels: conceptApproved

#17958 Updated the symbols, gestures, character descriptions files for Simplified Chinese
  source/locale/zh_CN/characterDescriptions.dic
  source/locale/zh_CN/gestures.ini
  source/locale/zh_CN/symbols.dic
Labels: conceptApproved
