Repository nvaccess/nvda, pull requests merged in 2025-01, with the labels that each got.

#17537 Add ability to add more constraints to bdDetect USB device registration
  source/bdDetect.py
  source/braille.py
  source/brailleDisplayDrivers/albatross/driver.py
  source/brailleDisplayDrivers/alva.py
  source/brailleDisplayDrivers/baum.py
  source/brailleDisplayDrivers/brailleNote.py
  source/brailleDisplayDrivers/brailliantB.py
  source/brailleDisplayDrivers/eurobraille/driver.py
  source/brailleDisplayDrivers/freedomScientific.py
  source/brailleDisplayDrivers/handyTech.py
  source/brailleDisplayDrivers/hidBrailleStandard.py
  source/brailleDisplayDrivers/hims.py
  source/brailleDisplayDrivers/nattiqbraille.py
  source/brailleDisplayDrivers/seikantk.py
  source/brailleDisplayDrivers/superBrl.py
  source/hwPortUtils.py
  source/winAPI/constants.py
  user_docs/en/changes.md
Labels: conceptApproved

#17578 Remove problematic euro symbol regex in fi
  source/locale/fi/symbols.dic
Labels: conceptApproved

#17582 Message Dialog API take 2
  projectDocs/dev/developerGuide/developerGuide.md
  requirements.txt
  source/documentationUtils.py
  source/gui/__init__.py
  source/gui/blockAction.py
  source/gui/exit.py
  source/gui/guiHelper.py
  source/gui/message.py
  source/gui/nvdaControls.py
  source/updateCheck.py
  source/visionEnhancementProviders/screenCurtain.py
  tests/system/robot/startupShutdownNVDA.robot
  tests/unit/test_messageDialog.py
  user_docs/en/changes.md
Labels: conceptApproved

#17581 Sanitize browseableMessage html
  source/ui.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#17604 Split Java Access Bridge calls to fix NVDA crashes when selecting whole text in specific source files in Android studio
  source/JABHandler.py
  user_docs/en/changes.md
Labels: conceptApproved

#17499 MS Word documents: report when headings are collapsed in both speech and braille.
  nvdaHelper/remote/WinWord/Constants.h
  nvdaHelper/remote/winword.cpp
  source/NVDAObjects/UIA/wordDocument.py
  source/NVDAObjects/window/winword.py
  source/braille.py
  source/speech/speech.py
  user_docs/en/changes.md
Labels: conceptApproved

#17631 Enable whole-program optimization when compiling eSpeak-NG
  nvdaHelper/espeak/sconscript
Labels: conceptApproved

#17598 Remove 'Automatically set system focus to focusable elements'
  source/browseMode.py
  source/config/configSpec.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: api-breaking-change, conceptApproved

#17505 Add "Only in edit controls" mode for typing echo
  source/NVDAObjects/behaviors.py
  source/NVDAObjects/inputComposition.py
  source/config/configFlags.py
  source/config/configSpec.py
  source/config/profileUpgradeSteps.py
  source/globalCommands.py
  source/gui/settingsDialogs.py
  source/speech/speech.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: api-breaking-change, conceptApproved

#17599 Fix SAPI 4 driver
  source/autoSettingsUtils/driverSetting.py
  source/gui/settingsDialogs.py
  source/synthDrivers/_sapi4.py
  source/synthDrivers/sapi4.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: api-breaking-change, conceptApproved

#17642 Fix up config upgrade steps from schema version 14 to 15
  source/config/profileUpgradeSteps.py
Labels: blocked/needs-info

#17635 Fix EcoBraille and Lilly braille display drivers
  source/braille.py
Labels: conceptApproved
