Repository nvaccess/nvda, pull requests merged in 2025-07, with the labels that each got.

#18219 Fix braille word wrap
  source/braille.py
  tests/unit/test_braille/test_calculateWindowRowBufferOffsets.py
  user_docs/en/changes.md
Labels: blocked/merge-conflicts, conceptApproved, merge-early, blocked/needs-testing

#18379 Minor fixups to projectDocs
  projectDocs/issues/triage.md
  projectDocs/translating/github.md
Labels: conceptApproved

#17733 Excel: for selection covering more than one cell, announce the active cell when pressing Enter or Tab rather than the whole selection range
  source/NVDAObjects/window/excel.py
  user_docs/en/changes.md
Labels: conceptApproved

#18438 Fix app module loading on X64
  source/appModuleHandler.py
Labels: conceptApproved, epic/64bit-migration

#18453 Fetch translations from crowdin
  .github/workflows/add-new-language.yml
  .github/workflows/fetch-crowdin-translations.yml
  source/l10nUtil.py
Labels: conceptApproved

#18514 Fix l10n regex for unnamed percentages
  source/NVDAObjects/UIA/__init__.py
  source/core.py
  source/globalCommands.py
  source/gui/addonGui.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/configProfiles.py
  source/gui/nvdaControls.py
  source/l10nUtil.py
  tests/unit/test_l10nUtil.py
Labels: conceptApproved

#18506 Added ability to sort add-ons by last tested version
  source/gui/addonStoreGui/controls/details.py
  source/gui/addonStoreGui/viewModels/addonList.py
  user_docs/en/changes.md
Labels: conceptApproved

#18244 Deploy with GitHub actions
  .github/workflows/testAndPublish.yml
  ci/README.md
  ci/scripts/setBuildVersionVars.ps1
Labels: conceptApproved

#18572 Update symbols.dic
  source/locale/bs/symbols.dic
Labels: conceptApproved

#18300 Fix SAPI5
  source/synthDrivers/sapi4.py
  source/synthDrivers/sapi5.py
  user_docs/en/changes.md
Labels: merge-early
