Repository nvaccess/nvda, pull requests merged in 2025-03, with the labels that each got.

#17666 Improve NVDA's coding standards
  projectDocs/dev/codingStandards.md
Labels: conceptApproved

#17770 Always re-enable audio ducking when starting a new utterance
  source/audioDucking.py
  user_docs/en/changes.md
Labels: conceptApproved

#17757 Fix parsing error in simplified Chinese characterDescriptions
  source/locale/zh_CN/characterDescriptions.dic
Labels: conceptApproved

#17644 Implement an extension point deprecation strategy
  projectDocs/dev/deprecations.md
  source/braille.py
  source/brailleViewer/__init__.py
  source/extensionPoints/util.py
  tests/system/libraries/SystemTestSpy/speechSpyGlobalPlugin.py
  tests/unit/__init__.py
  tests/unit/extensionPointTestHelpers.py
  tests/unit/test_braille/test_handlerExtensionPoints.py
Labels: conceptApproved

#17744 Add pyright for static type checking
  .pre-commit-config.yaml
  projectDocs/testing/automated.md
  pyproject.toml
  requirements.txt
  runlint.bat
  source/NVDAObjects/IAccessible/__init__.py
  source/NVDAObjects/IAccessible/adobeAcrobat.py
  source/NVDAObjects/IAccessible/ia2Web.py
  source/NVDAObjects/UIA/winConsoleUIA.py
  source/UIAHandler/_remoteOps/instructions/_base.py
  source/UIAHandler/_remoteOps/instructions/textRange.py
  source/UIAHandler/_remoteOps/remoteAPI.py
  source/__builtins__.pyi
  source/addonStore/settings.py
  source/annotation.py
  source/appModules/poedit.py
  source/baseObject.py
  source/browseMode.py
  source/buildVersion.py
  source/config/__init__.py
  source/config/featureFlagEnums.py
  source/extensionPoints/util.py
  source/gui/addonStoreGui/controls/actions.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/message.py
  source/gui/nvdaControls.py
  source/gui/settingsDialogs.py
  source/hwPortUtils.py
  source/mathPres/mathPlayer.py
  source/oleacc.py
  source/speech/commands.py
  source/synthDriverHandler.py
  source/synthDrivers/oneCore.py
  source/synthDrivers/sapi5.py
  source/updateCheck.py
  source/utils/urlUtils.py
  source/virtualBuffers/gecko_ia2.py
  source/winAPI/_wtsApi32.py
  source/winAPI/messageWindow.py
  source/winUser.py
  tests/system/libraries/SystemTestSpy/speechSpyGlobalPlugin.py
  tests/unit/__init__.py
  tests/unit/test_UIARemoteOps/test_highLevel/test_errorHandling.py
  tests/unit/test_addonHandler/test_addonsState.py
  tests/unit/test_baseObject.py
  typings/_buildVersion/__init__.pyi
  user_docs/en/changes.md
Labels: api-breaking-change, release/blocking, conceptApproved

#17745 Remove lint from AppVeyor
  appveyor.yml
  appveyor/README.md
  appveyor/scripts/tests/lintCheck.ps1
Labels: conceptApproved

#17769 Add a developer task issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/developer_facing_changes.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/special_case_issue.md
  projectDocs/issues/githubIssueTemplateExplanationAndExamples.md
Labels: conceptApproved

#17774 Add verbose debug log for SAPI4
  source/synthDrivers/sapi4.py
Labels: conceptApproved

#17310 add validation of update mirror urls
  source/gui/settingsDialogs.py
  source/updateCheck.py
  user_docs/en/changes.md
Labels: api-breaking-change, release/blocking, conceptApproved

#17580 Remote Access
  nvdaHelper/interfaces/nvdaControllerInternal/nvdaControllerInternal.acf
  nvdaHelper/interfaces/nvdaControllerInternal/nvdaControllerInternal.idl
  nvdaHelper/local/nvdaControllerInternal.c
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/remote/nvdaHelperRemote.def
  projectDocs/dev/developerGuide/developerGuide.md
  requirements.txt
  source/NVDAHelper.py
  source/config/__init__.py
  source/config/configSpec.py
  source/config/profileUpgradeSteps.py
  source/core.py
  source/globalCommands.py
  source/gui/guiHelper.py
  source/gui/settingsDialogs.py
  source/nvda_slave.pyw
  source/remoteClient/__init__.py
  source/remoteClient/bridge.py
  source/remoteClient/client.py
  source/remoteClient/configuration.py
  source/remoteClient/connectionInfo.py
  source/remoteClient/cues.py
  source/remoteClient/dialogs.py
  source/remoteClient/input.py
  source/remoteClient/localMachine.py
  source/remoteClient/menu.py
  source/remoteClient/protocol.py
  source/remoteClient/secureDesktop.py
  source/remoteClient/serializer.py
  source/remoteClient/server.py
  source/remoteClient/session.py
  source/remoteClient/transport.py
  source/remoteClient/urlHandler.py
  source/setup.py
  source/speech/__init__.py
  source/speech/extensions.py
  source/speech/manager.py
  source/tones.py
  source/waves/clipboardPush.wav
  source/waves/clipboardReceive.wav
  source/waves/connected.wav
  source/waves/controlled.wav
  source/waves/controlling.wav
  source/waves/disconnected.wav
  tests/manual/remote.md
  tests/unit/test_remote/__init__.py
  tests/unit/test_remote/test_bridge.py
  tests/unit/test_remote/test_remote_client.py
  tests/unit/test_remote/test_serializer.py
  tests/unit/test_remote/test_transport.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: release/blocking, conceptApproved

#17590 Update devGuide for translating symbols, gestures, character descriptions
  .github/workflows/monitor-localisation-file-changes.yml
  projectDocs/dev/developerGuide/developerGuide.md
  projectDocs/translating/github.md
  projectDocs/translating/readme.md
Labels: release/blocking, conceptApproved, release/blocking-beta

#17806 Fix speech delay caused by audio ducking
  source/audioDucking.py
Labels: blocked/needs-product-decision
