Repository nvaccess/nvda, pull requests merged in 2025-02, with the labels that each got.

#17668 Update webhook
  appveyor.yml
  appveyor/scripts/deployScript.ps1
  appveyor/scripts/webhookSetup.ps1
Labels: conceptApproved

#17660 Add a payload argument to message dialog callbacks
  projectDocs/dev/developerGuide/developerGuide.md
  source/gui/message.py
  source/synthDrivers/sapi4.py
Labels: conceptApproved

#17641 Delete outdated translated copies of developer guide
  user_docs/de/developerGuide.md
  user_docs/pt_BR/developerGuide.md
Labels: conceptApproved

#17652 No longer sentence nav in VS Code
  source/NVDAObjects/window/winword.py
  source/appModules/code.py
  source/editableText.py
  user_docs/en/changes.md
Labels: conceptApproved

#17600 Remove contributors file from NVDA, read license as HTML
  contributors.txt
  copying.txt
  source/documentationUtils.py
  source/gui/__init__.py
  source/gui/startupDialogs.py
  source/setup.py
  source/systemUtils.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17597 Add ability to customize automatic update channels for add-ons
  source/addonStore/dataManager.py
  source/addonStore/models/channel.py
  source/addonStore/network.py
  source/addonStore/settings.py
  source/config/configSpec.py
  source/gui/addonStoreGui/controls/actions.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/controls/storeDialog.py
  source/gui/addonStoreGui/viewModels/action.py
  source/gui/settingsDialogs.py
  tests/unit/test_config.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: api-breaking-change, conceptApproved

#17610 Add rate boost support for SAPI5 voices
  nvdaHelper/espeak/sconscript
  nvdaHelper/espeak/sonic.def
  source/synthDrivers/_sonic.py
  source/synthDrivers/sapi5.py
  user_docs/en/changes.md
Labels: conceptApproved

#17648 Add leading silence detection and removal logic
  nvdaHelper/local/nvdaHelperLocal.def
  nvdaHelper/local/silenceDetect.h
  nvdaHelper/local/wasapi.cpp
  projectDocs/dev/developerGuide/developerGuide.md
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/nvwave.py
  source/speech/manager.py
  source/synthDriverHandler.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved, merge-early

#17676 Fix scrolling to anchor links pointing to the object containing the virtual caret
  source/browseMode.py
  user_docs/en/changes.md
Labels: conceptApproved

#17678 Finish WinMM Removal
  source/config/profileUpgradeSteps.py
  source/gui/settingsDialogs.py
  source/nvwave.py
  source/utils/mmdevice.py
  tests/unit/test_config.py
  user_docs/en/changes.md
Labels: api-breaking-change, conceptApproved

#17651 Ensure screen stays on during say all
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/inputCore.py
  source/speech/sayAll.py
  source/systemUtils.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17707 Fix index skipping when trimming leading silence
  nvdaHelper/local/wasapi.cpp
Labels: conceptApproved

#17545 MS Word: The result of Word commands to expand or collapse a heading is now reported
  source/NVDAObjects/window/winword.py
  source/appModules/winword.py
  user_docs/en/changes.md
Labels: conceptApproved

#17682 Add fully automatic add-on updates
  source/addonHandler/__init__.py
  source/addonStore/dataManager.py
  source/addonStore/models/addon.py
  source/addonStore/models/status.py
  source/config/configFlags.py
  source/config/configSpec.py
  source/gui/addonStoreGui/controls/details.py
  source/gui/addonStoreGui/controls/messageDialogs.py
  source/gui/addonStoreGui/viewModels/store.py
  source/gui/message.py
  source/gui/settingsDialogs.py
  source/utils/schedule.py
  tests/unit/test_util/test_schedule.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17727 Refined Chinese character descriptions and added entries for ancient characters and tongjiazi (phonetic loan characters).
  source/locale/zh_CN/characterDescriptions.dic
Labels: conceptApproved

#17714 Fix prevent display from turning off
  source/config/configSpec.py
  source/gui/settingsDialogs.py
  source/systemUtils.py
  user_docs/en/userGuide.md
Labels: conceptApproved

#17717 Add-on Store: Download without duplicates to override incompatibilities.
  source/gui/addonStoreGui/viewModels/store.py
Labels: conceptApproved

#17718 Make SAPI4 voices use WASAPI
  projectDocs/design/synthesizers.md
  source/synthDrivers/_sapi4.py
  source/synthDrivers/sapi4.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: release/blocking, conceptApproved, merge-early

#17715 Manually refresh the recognized content with `NVDA+f5` in a recognition result
  source/contentRecog/recogUi.py
  user_docs/en/changes.md
  user_docs/en/userGuide.md
Labels: conceptApproved

#17724 Avoid error in PowerPoint slideshows when focus highlighting is on
  source/appModules/powerpnt.py
Labels: conceptApproved
